import { readFileSync } from 'node:fs'
import { join } from 'node:path'

import { describe, expect, it } from 'vitest'

describe('ref.1 processing shell (ui.2)', () => {
  it('ProcessingScreen module and ref1 CSS exist', () => {
    const tsxPath = join(process.cwd(), 'src/renderer/src/pages/ProcessingScreen.tsx')
    const centerPath = join(
      process.cwd(),
      'src/renderer/src/pages/processing-ref1-center-parts.tsx'
    )
    const partsPath = join(process.cwd(), 'src/renderer/src/pages/processing-ref1-parts.tsx')
    const dataPath = join(process.cwd(), 'src/renderer/src/pages/processing-ref1-data.ts')
    const cssPath = join(process.cwd(), 'src/renderer/src/assets/ref1-processing.css')
    const iconsCssPath = join(process.cwd(), 'src/renderer/src/assets/ref1-processing-icons.css')
    const chromePath = join(process.cwd(), 'src/renderer/src/components/NeonWindowChrome.tsx')
    const tsx = readFileSync(tsxPath, 'utf8')
    const center = readFileSync(centerPath, 'utf8')
    const parts = readFileSync(partsPath, 'utf8')
    const data = readFileSync(dataPath, 'utf8')
    const css = readFileSync(cssPath, 'utf8')
    const iconsCss = readFileSync(iconsCssPath, 'utf8')
    const chrome = readFileSync(chromePath, 'utf8')

    expect(tsx).toContain('ProcessingScreen')
    expect(tsx).toContain('NeonReferenceOverlay')
    expect(parts).toContain('TrackRow')
    expect(parts).toContain('ProcessingFfmpegRail')
    expect(css).toContain('processing-shell')
    expect(css).toContain('grid-template-areas:')
    expect(css).toContain("'sidebar editor rail'")
    expect(css).toContain('grid-area: editor')
    expect(css).toContain('grid-area: rail')
    expect(css).toContain('processing-timeline__playhead')
    expect(center).toContain('ProcessingEditorCenterBody')
    expect(tsx).toContain('ProcessingEditorCenterBody')
    expect(center).toContain('processing-timeline__playhead')
    expect(css).toContain('--processing-timeline-lane-inset')
    expect(tsx).not.toContain('НАВИГАЦИЯ')
    expect(tsx).toContain('processing-sidebar__nav-block')
    expect(tsx).not.toContain('processing-sidebar__media')
    expect(tsx).not.toContain('МЕДИАТЕКА')
    expect(tsx).toContain('processing-sidebar__footer')
    expect(tsx).toContain('processing-util-btn--tools')
    expect(iconsCss).toContain('.processing-util-btn--tools')
    expect(tsx).toContain('processing-sidebar__gpu-stats')
    expect(css).toContain('.processing-sidebar__footer')
    expect(tsx).toContain('<span>Диск</span>')
    expect(data).toContain('PROCESSING_TIMELINE_PLAYHEAD_PERCENT')
    expect(tsx).toContain('processing-center__head--png')
    expect(tsx).not.toContain('processing-center__eyebrow')
    expect(tsx).not.toContain('processing-center__summary')
    expect(data).toContain('PROCESSING_CENTER_EYEBROW')
    expect(data).toContain('PROCESSING_SELECTION_TIMECODE')
    expect(data).toContain("label: 'Выделение'")
    expect(data).toContain('PROCESSING_RAIL_PRESETS')
    expect(parts).toContain('processing-rail__preset-list')
    expect(parts).toContain('processing-rail__preset-row--active')
    expect(css).toContain('.processing-rail__preset-row--active')
    expect(tsx).toContain('СИСТЕМА')
    expect(data).toContain('PROCESSING_HEAD_CHIP')
    expect(data).toContain('PROCESSING_PREVIEW_BADGE')
    expect(data).toContain('PROCESSING_PREVIEW_ZOOM_PERCENT')
    expect(center).toContain('PROCESSING_PREVIEW_BADGE')
    expect(parts).toContain('processing-clip__duration')
    expect(parts).toContain('processing-clip__thumb-shine')
    expect(css).toContain('.processing-clip__thumb-shine')
    expect(css).toContain('.processing-statusbar__item--cyan')
    expect(data).toContain('accent:')
    expect(css).toContain('processing-clip__wave-bars')
    expect(css).toContain('ref1-processing-icons.css')
    expect(tsx).toContain('processing-nav__icon--${item.slug}')
    expect(center).toContain('processing-preview__scene')
    expect(center).toContain('processing-timeline__body')
    expect(center).toContain('processing-timeline__tracks')
    expect(center).toContain('processing-timeline__ruler-ticks-major')
    expect(center).toContain('processing-media-glyph--pause')
    expect(css).toContain('processing-timeline__ruler-ticks')
    expect(css).toContain('.processing-timeline__ruler-ticks-major')
    expect(css).toContain('.processing-timeline__tracks')
    expect(css).toContain('.processing-preview__transport-playback .vn-btn--icon:hover')
    expect(css).toContain('.processing-rail__export-btn:hover')
    expect(css).toContain('processing-statusbar__center')
    expect(parts).not.toContain('processing-rail__subtitle')
    expect(parts).toContain('processing-rail__head--png')
    expect(parts).not.toContain('processing-rail__summary')
    expect(data).toContain('PROCESSING_RAIL_SUMMARY')
    expect(data).toContain('PROCESSING_RAIL_CHIP')
    expect(css).toContain('.processing-rail__summary')
    expect(css).toContain('color: var(--vn-color-cyan-electric)')
    expect(center).toContain('trackHint="Высокая громк."')
    expect(center).toContain('showLinkMarkers')
    expect(parts).toContain('processing-clip-link')
    expect(parts).toContain('processing-clip__link-mark')
    expect(data).toContain('linked: true')
    expect(iconsCss).toContain('.processing-clip__link-mark')
    expect(css).toContain('.processing-statusbar--dense')
    expect(tsx).toContain('processing-statusbar--dense')
    expect(css).toContain('.processing-clip-link::after')
    expect(css).toContain('.processing-clip-link')
    expect(parts).toContain('processing-rail__preset-card')
    expect(parts).toContain('processing-rail__preset-head')
    expect(parts).toContain('processing-rail__preset-meta')
    expect(data).toContain('active: true')
    expect(css).toContain('.processing-media-cat--active')
    expect(css).toContain('.processing-nav__item:hover')
    expect(css).toContain('.processing-preview__saved::before')
    expect(css).toContain('.processing-rail__preset-card:hover')
    expect(center).toContain('processing-tool-glyph--select')
    expect(center).toContain('processing-transport-glyph--loop')
    expect(center).toContain('processing-preview__transport-tool')
    expect(css).toContain('.processing-preview__transport-tool:hover')
    expect(css).toContain('.processing-media-cat--active .processing-media-cat__glyph')
    expect(center).toContain('processing-tool-glyph--group')
    expect(center).toContain('processing-tool-glyph--pen')
    expect(center).toContain('processing-tool-glyph--layers')
    expect(data).toContain('НОВЫЙ СЕЗОН.vlxrp')
    expect(data).toContain("export const PROCESSING_STATUS_READY = 'Готово'")
    expect(css).toContain('processing-playhead-glow')
    expect(data).toContain('export const V2_CLIPS: readonly ProcessingClipMock[] = []')
    expect(data).toContain('export const V3_CLIPS: readonly ProcessingClipMock[] = []')
    expect(parts).toContain('processing-timeline__lane--empty')
    expect(css).toContain('.processing-timeline__lane--empty')
    expect(css).toContain('.processing-preview__fit:hover:not(:disabled)')
    expect(css).toContain('.processing-preview__chrome-btn:hover:not(:disabled)')
    expect(data).toContain('PROCESSING_MEDIA_LIBRARY')
    expect(data).toContain('PROCESSING_CENTER_SUMMARY')
    expect(data).toContain('PROCESSING_STATUS_READY')
    expect(tsx).toContain('PROCESSING_STATUS_READY')
    expect(css).toContain('.processing-center__head--png')
    expect(css).toContain('.processing-rail__head--png')
    expect(css).toContain('processing-clip:hover')
    expect(css).toContain('processing-rail__section:hover')
    expect(data).toContain('PROCESSING_PREVIEW_SAVED_LABEL')
    expect(data).toContain('PROCESSING_PREVIEW_VOLUME_PERCENT')
    expect(tsx).toContain('processing-sidebar__brand-edition')
    expect(center).toContain('processing-preview__volume-val')
    expect(css).toContain('.processing-preview__volume:hover')
    expect(css).toContain('.processing-clip--wave:hover')
    expect(css).toContain('processing-timeline__track-tools .processing-track-icon:hover')
    expect(css).toContain('prefers-reduced-motion')
    expect(data).toContain('PROCESSING_RAIL_AUDIO_FIELDS')
    expect(data).toContain('highlight: true')
    expect(tsx).toContain('ProcessingFfmpegRail')
    expect(css).toContain('processing-clip--highlight')
    expect(css).toContain('processing-clip__badge--fx')
    expect(center).toContain('processing-preview__skyline')
    expect(center).toContain('processing-preview__horizon')
    expect(center).toContain('processing-preview__ground-mist')
    expect(tsx).toContain('processing-sidebar__gpu-tag')
    expect(tsx).toContain('Загрузка:')
    expect(tsx).toContain('Температура:')
    expect(data).toContain('PROCESSING_GPU')
    expect(data).toContain('PROCESSING_STORAGE')
    expect(css).toContain('.processing-preview__watermark::before')
    expect(iconsCss).toContain('.processing-nav__item--active .processing-nav__icon--processing')
    expect(css).toContain('.processing-sidebar__project:hover')
    expect(css).toContain('.processing-sidebar__gpu-meter-fill--load')
    expect(css).toContain('.processing-preview__car::before')
    expect(css).toContain('.processing-sidebar__gpu:hover')
    expect(css).toContain('processing-preview__scanlines')
    expect(data).toContain('thumbTone:')
    expect(css).toContain('processing-clip--tone-violet')
    expect(data).toContain('PROCESSING_TIMECODE')
    expect(data).toContain('PROCESSING_TIMELINE_ZOOM_PERCENT')
    expect(center).toContain('processing-timeline__zoom-val')
    expect(center).toContain('processing-timeline__snap-pill--on')
    expect(tsx).toContain('processing-statusbar__tc')
    expect(css).toContain('.processing-timeline__snap-pill--on')
    expect(css).toContain('.processing-statusbar__tc')
    expect(css).toContain('.processing-timeline__track--active .processing-timeline__lane')
    expect(center).toContain('processing-preview__transport-playback')
    expect(css).toContain('--processing-rail-w')
    expect(center).toContain('processing-timeline__snap-pill')
    expect(tsx).toContain('processing-statusbar__item')
    expect(center).toContain('processing-preview__saved')
    expect(css).toContain('processing-media-cat__count')
    expect(parts).toContain('processing-track-icon--mute')
    expect(css).toContain('processing-timeline__keyframe')
    expect(parts).toContain('CLIP_WAVEFORM_BAR_COUNT')
    expect(chrome).toContain('requestMinimize')
    expect(chrome).toContain('requestClose')
  })

  it('bootstrap defaults to ref.1 route', () => {
    const bootstrap = readFileSync(
      join(process.cwd(), 'src/renderer/src/app-neon-bootstrap.tsx'),
      'utf8'
    )
    expect(bootstrap).toContain("return 'ref1'")
    expect(bootstrap).toContain('ProcessingScreen')
  })
})
