import { readFileSync } from 'node:fs'
import { join } from 'node:path'

import { describe, expect, it } from 'vitest'

import { loadRef1ProcessingShellAssets } from './neon-processing-shell-fixtures'

describe('ref.1 processing shell (ui.2)', () => {
  it('ProcessingScreen module and ref1 CSS exist', () => {
    const { tsx, center, parts, data, css, iconsCss, chrome, brandCss } =
      loadRef1ProcessingShellAssets()

    expect(tsx).toContain('ProcessingScreen')
    expect(tsx).toContain('NeonReferenceOverlay')
    expect(tsx).toContain('NeonSidebarBrand')
    expect(tsx).not.toContain('processing-sidebar__logo')
    expect(parts).toContain('TrackRow')
    expect(parts).toContain('ProcessingFfmpegRail')
    expect(css).toContain('processing-shell')
    expect(css).toContain('grid-template-areas:')
    expect(css).toContain("'sidebar editor rail'")
    expect(css).toContain('grid-area: editor')
    expect(css).toContain('grid-area: rail')
    expect(css).toContain('processing-timeline__playhead')
    expect(center).toContain('ProcessingEditorCenterBody')
    expect(tsx).toContain('ProcessingEditorCenterBody')
    expect(center).toContain('processing-timeline__playhead')
    expect(css).toContain('--processing-timeline-lane-inset')
    expect(css).toContain('--processing-timeline-track-gap: 0.26rem')
    expect(tsx).not.toContain('НАВИГАЦИЯ')
    expect(tsx).toContain('processing-sidebar__nav-block')
    expect(tsx).not.toContain('МЕДИАТЕКА')
    expect(tsx).not.toContain('processing-sidebar__footer')
    expect(tsx).not.toContain('processing-util-btn--settings')
    expect(tsx).not.toContain('processing-util-btn--tools')
    expect(tsx).not.toContain('processing-util-btn--power')
    expect(tsx).toContain('processing-sidebar__gpu-stats')
    expect(css).toContain('processing-sidebar__gpu-stats strong')
    expect(css).toContain('clamp(13.5rem, 13.75vw, 15.25rem)')
    expect(css).toContain('--processing-timeline-label-w: 2.78rem')
    expect(css).toContain('clamp(20rem, 21.5vw, 24.5rem)')
    expect(tsx).toContain('layout="ref1"')
    expect(brandCss).toContain('.neon-sidebar-brand--ref1')
    expect(tsx).toContain('<span>Диск</span>')
    expect(data).toContain('PROCESSING_TIMELINE_PLAYHEAD_PERCENT')
    expect(center).toContain('PROCESSING_TIMELINE_PLAYHEAD_PERCENT')
    expect(center).toContain('processing-timeline__body')
    expect(center).toContain('--processing-timeline-playhead')
    expect(tsx).toContain('processing-center__head--png')
    expect(tsx).not.toContain('processing-center__eyebrow')
    expect(data).toContain('PROCESSING_CENTER_EYEBROW')
    expect(data).toContain('PROCESSING_SELECTION_TIMECODE')
    expect(data).toContain("label: 'Выделение'")
    expect(data).toContain('PROCESSING_RAIL_PRESETS')
    expect(parts).toContain('processing-rail__section--video')
    expect(parts).toContain('processing-rail__section-hint')
    expect(data).toContain('PROCESSING_RAIL_SECTION_HINTS')
    expect(parts).toContain('processing-rail__preset-list')
    expect(parts).toContain('processing-rail__preset-row--active')
    expect(css).toContain('.processing-rail__preset-row--active')
    expect(tsx).toContain('showEdition={false}')
    expect(tsx).toContain('Система')
    expect(tsx).not.toContain('СИСТЕМА')
    expect(data).toContain('PROCESSING_HEAD_CHIP')
    expect(tsx).not.toContain('PROCESSING_HEAD_CHIP')
    expect(tsx).not.toContain('processing-center__head-chip')
    expect(tsx).not.toContain('PROCESSING_STORAGE')
    expect(tsx).not.toContain('PROCESSING_MEDIA_LIBRARY')
    expect(tsx).not.toContain('PROCESSING_PROJECT_FILES')
    expect(tsx).not.toContain('processing-sidebar__gpu-meters')
    expect(tsx).not.toContain('processing-sidebar__gpu-tag')
    expect(center).not.toContain('processing-preview__saved')
    expect(center).not.toContain('PROCESSING_PREVIEW_SAVED_LABEL')
    expect(center).not.toContain('processing-preview__badge')
    expect(center).not.toContain('processing-preview__overlays')
    expect(data).toContain('PROCESSING_REF1_DEMO_PREVIEW_URL')
    expect(data).toContain('thumbDemoId')
    expect(center).toContain('processing-preview__scene--ref')
    expect(center).toContain('processing-preview__scene-demo')
    expect(center).toContain('PROCESSING_REF1_DEMO_PREVIEW_URL')
    expect(parts).toContain('processing-clip__film-demo')
    expect(parts).toContain('processingRef1DemoClipThumbUrl')
    expect(css).toContain('.processing-clip--highlight::after')
    expect(css).toContain('.processing-rail__export-btn')
    expect(css).toContain('.processing-rail__slider-fill--crf::after')
    expect(css).toMatch(/\.processing-shell\s*\{[\s\S]*#0b0b14/)
    expect(css).toContain('.processing-statusbar__val--cyan')
    expect(css).toMatch(/\.processing-statusbar__right[\s\S]*border-left:/)
    expect(css).toMatch(
      /\.processing-statusbar--dense \.processing-statusbar__center[\s\S]*border-left:/
    )
    expect(data).toContain('accent:')
    expect(css).toContain('processing-clip__wave-bars')
    expect(css).toContain('ref1-processing-icons.css')
    expect(tsx).toContain('processing-nav__icon--${item.slug}')
    expect(center).toContain('processing-preview__scene')
    expect(center).not.toContain('processing-preview__horizon')
    expect(center).not.toContain('processing-preview__overlays')
    expect(center).not.toContain('processing-preview__badge')
    expect(center).toContain('processing-timeline__body')
    expect(center).toContain('processing-timeline__tracks')
    expect(center).toContain('processing-timeline__ruler-ticks-major')
    expect(center).toContain('processing-media-glyph--pause')
    expect(center).toContain('processing-media-glyph--skip-start')
    expect(center).toContain('processing-media-glyph--forward')
    expect(center).toContain('title="В начало"')
    expect(center).toContain('--processing-preview-volume-pct')
    expect(css).toContain('--processing-preview-volume-pct')
    expect(css).toContain('.processing-rail__select:hover')
    expect(css).toContain('.processing-rail__field--fps')
    expect(parts).toContain('processing-rail__field--fps')
    expect(css).toContain('.processing-preview__transport-playback .vn-btn--icon:disabled')
    expect(css).toContain('.processing-clip--thumb .processing-clip__label')
    expect(css).toContain('processing-timeline__ruler-ticks')
    expect(css).toContain('.processing-timeline__ruler-ticks-major')
    expect(css).toContain('.processing-timeline__track + .processing-timeline__track')
    expect(css).toContain('.processing-statusbar__tc--magenta')
    expect(css).toMatch(/\.processing-ring \{[\s\S]*filter: none/)
    expect(css).toContain('.processing-rail__section:not([open]) summary::after')
    expect(css).toMatch(/\.processing-sidebar__nav-block \{[\s\S]*border-radius/)
    expect(css).toMatch(/\.processing-rail__slider-mock em[\s\S]*text-shadow: none/)
    expect(css).toMatch(
      /\.processing-preview__transport-playback \.vn-btn--play[\s\S]*inset 0 0 8px rgba\(168, 85, 247, 0\.12\)/
    )
    expect(css).toMatch(/\.processing-rail__switch--on[\s\S]*border: 1px solid/)
    expect(css).toMatch(/\.processing-rail__preset-row--active[\s\S]*inset 3px 0 0/)
    expect(css).toContain('.processing-timeline__tracks')
    expect(css).toContain('.processing-preview__transport-playback .vn-btn--icon:hover')
    expect(css).toContain('.processing-rail__export-btn:hover')
    expect(css).toContain('processing-statusbar__center')
    expect(parts).toContain('processing-rail__subtitle')
    expect(parts).not.toContain('processing-rail__summary')
    expect(parts).not.toContain('processing-rail__head-chip')
    expect(parts).toContain('processing-rail__head--png')
    expect(parts).toContain('processing-rail__head-top')
    expect(data).toContain('PROCESSING_RAIL_SUBTITLE')
    expect(css).toContain('.processing-rail__subtitle {')
    expect(css).not.toContain('.processing-rail__summary {')
    expect(css).not.toContain('.processing-rail__eyebrow {')
    expect(css).not.toContain('.processing-rail__head-chip {')
    expect(css).not.toContain('.processing-center__head-chip {')
    expect(css).not.toContain('.processing-center__summary {')
    expect(css).not.toContain('.processing-center__head-tools {')
    expect(css).not.toContain('.processing-center__eyebrow {')
    expect(css).not.toContain('.processing-sidebar__gpu-tag {')
    expect(css).not.toContain('.processing-timeline__snap-pill {')
    expect(center).toContain('--processing-timeline-zoom-pct')
    expect(css).toContain('--processing-timeline-zoom-pct')
    expect(css).not.toContain('.processing-timeline__zoom-val {\n  display: none')
    expect(css).toContain('color: var(--vn-color-cyan-electric)')
    expect(center).toContain('PROCESSING_A1_TRACK_HINT')
    expect(center).toContain('showLinkMarkers')
    expect(parts).toContain('processing-clip-link')
    expect(parts).toContain('processing-clip__link-mark')
    expect(parts).toContain('processing-clip--linked')
    expect(parts).toContain('processing-timeline__track--video-empty')
    expect(css).toContain('.processing-timeline__lane--envelope::before')
    expect(data).toContain('linked: true')
    expect(iconsCss).toContain('.processing-clip__link-mark')
    expect(css).toContain('.processing-statusbar--dense')
    expect(tsx).toContain('processing-statusbar--dense')
    expect(css).toContain('.processing-clip-link::after')
    expect(css).toContain('.processing-clip-link')
    expect(parts).toContain('processing-rail__preset-card')
    expect(parts).toContain('processing-rail__preset-head')
    expect(parts).toContain('processing-rail__preset-meta')
    expect(data).toContain('active: true')
    expect(css).toContain('.processing-nav__item:hover')
    expect(css).toContain('.processing-preview__saved::before')
    expect(css).toContain('.processing-rail__preset-card:hover')
    expect(center).toContain('processing-tool-glyph--select')
    expect(center).not.toContain('processing-transport-glyph--crop')
    expect(center).toContain('--processing-timeline-playhead')
    expect(center).toContain('processing-preview__transport-tool')
    expect(css).toContain('.processing-preview__transport-tool:hover')
    expect(center).not.toContain('processing-tool-glyph--group')
    expect(center).not.toContain('processing-tool-glyph--cloud')
    expect(center).not.toContain('processing-timeline__snap-pill')
    expect(center).not.toContain('processing-tool-glyph--layers')
    expect(center).toContain('processing-tool-glyph--blade')
    expect(center).toContain('processing-timeline__tool--link-on')
    expect(css).toContain('.processing-timeline__tool--link-on')
    expect(css).toContain('.processing-timeline__playhead-bubble {')
    expect(css).toContain('background: rgba(168, 85, 247, 0.96)')
    expect(css).toContain('.processing-timeline__zoom-val {')
    expect(css).toContain('border: 1px solid rgba(168, 85, 247, 0.2)')
    expect(css).toMatch(/\.processing-preview__volume-val[\s\S]*text-shadow: none/)
    expect(css).toContain(
      'linear-gradient(90deg, rgba(168, 85, 247, 0.82), rgba(124, 58, 237, 0.52)'
    )
    expect(css).toContain('.processing-nav__item--active .processing-nav__icon')
    expect(css).toMatch(/\.processing-preview__tc-box[\s\S]*border-radius: var\(--vn-radius-pill\)/)
    expect(css).toMatch(
      /\.processing-timeline__track-hint[\s\S]*inset 0 0 8px rgba\(46, 213, 115, 0\.12\)/
    )
    expect(css).toMatch(
      /\.processing-rail__section--video\[open\][\s\S]*inset 0 0 10px rgba\(168, 85, 247, 0\.08\)/
    )
    expect(css).toMatch(/\.processing-sidebar__gpu-spark-bars[\s\S]*filter: none/)
    expect(css).toMatch(/\.processing-statusbar--dense \.processing-statusbar__tc/)
    expect(css).toMatch(/\.processing-timeline__top[\s\S]*box-shadow: none/)
    expect(css).toMatch(/\.processing-sidebar__logo[\s\S]*text-shadow: none/)
    expect(css).toMatch(/\.processing-clip-link[\s\S]*inset 0 0 3px rgba\(168, 85, 247, 0\.14\)/)
    expect(css).toMatch(/\.processing-rail__section:not\(\[open\]\)[\s\S]*box-shadow: none/)
    expect(css).toMatch(
      /\.processing-clip--tone-cyan[\s\S]*inset 0 0 10px rgba\(59, 130, 246, 0\.08\)/
    )
    expect(iconsCss).toMatch(/\.processing-util-btn--settings[\s\S]*inset 0 0 6px/)
    expect(css).toMatch(/\.processing-preview \{[\s\S]*inset 0 0 0 1px rgba\(168, 85, 247, 0\.1\)/)
    expect(css).toMatch(
      /\.processing-preview__transport-playback[\s\S]*inset 0 0 10px rgba\(168, 85, 247, 0\.08\)/
    )
    expect(css).toMatch(
      /\.processing-sidebar__system:hover \.processing-ring--cpu[\s\S]*inset 0 0 10px/
    )
    expect(css).toMatch(/\.processing-rail \{[\s\S]*inset 1px 0 0 rgba\(168, 85, 247, 0\.06\)/)
    expect(css).toMatch(/\.processing-statusbar[\s\S]*box-shadow: none/)
    expect(css).toMatch(/\.processing-sidebar__nav-block[\s\S]*background: transparent/)
    expect(css).toMatch(
      /\.processing-statusbar__val--cyan[\s\S]*color: rgba\(96, 165, 250, 0\.92\)/
    )
    expect(css).toContain('.processing-preview__zoom-chevron')
    expect(css).toContain('.processing-timeline__track--active .processing-track-icon')
    expect(css).toMatch(
      /\.processing-timeline__track--active \.processing-timeline__label[\s\S]*text-shadow: none/
    )
    expect(css).toContain(
      '.processing-center__head--png .processing-center__head-main p:last-child'
    )
    expect(css).toContain('.processing-preview__volume-val {')
    expect(css).toContain('border-top: 1px solid rgba(255, 255, 255, 0.08)')
    expect(css).toContain('.processing-rail__section[open] summary::after')
    expect(css).toContain('.processing-rail__head--png .processing-rail__title')
    expect(css).toMatch(/\.processing-timeline__ruler-ticks[\s\S]*rgba\(148, 163, 184, 0\.14\) 0/)
    expect(css).toMatch(/\.processing-timeline__zoom input[\s\S]*rgba\(168, 85, 247, 0\.9\) 0%/)
    expect(css).toMatch(
      /\.processing-preview__zoom \{[\s\S]*border-radius: var\(--vn-radius-pill\)/
    )
    expect(css).toMatch(
      /\.processing-timeline__track--active \.processing-clip--thumb \.processing-clip__label/
    )
    expect(css).toMatch(
      /\.processing-preview__badge[\s\S]*inset 0 0 8px rgba\(168, 85, 247, 0\.14\)/
    )
    expect(css).toMatch(
      /\.processing-rail__slider-fill--crf::after[\s\S]*inset 0 0 5px rgba\(168, 85, 247, 0\.14\)/
    )
    expect(css).toContain('.processing-sidebar__brand-edition')
    expect(css).toContain('.processing-timeline__ruler-labels {')
    expect(css).toContain('letter-spacing: 0.03em')
    expect(css).toMatch(
      /\.processing-rail__select:hover \.processing-rail__chevron[\s\S]*text-shadow: none/
    )
    expect(css).toMatch(/\.processing-preview__watermark[\s\S]*filter: none/)
    expect(css).toMatch(
      /\.processing-rail__export-btn:hover:not\(:disabled\)[\s\S]*inset 0 0 14px rgba\(168, 85, 247, 0\.16\)/
    )
    expect(css).toContain('.processing-sidebar__section-title')
    expect(css).toMatch(
      /\.processing-sidebar__system:hover \.processing-ring--cpu[\s\S]*inset 0 0 10px/
    )
    expect(css).toContain('.processing-preview__ground-mist')
    expect(css).toContain('rgba(40, 10, 48, 0.5)')
    expect(css).not.toContain('.processing-rail__eyebrow {')
    expect(css).toMatch(/\.processing-sidebar__nav-block[\s\S]*overflow-y: auto/)
    expect(iconsCss).toMatch(
      /\.processing-chrome-glyph--fullscreen[\s\S]*inset 0 0 5px rgba\(59, 130, 246, 0\.14\)/
    )
    expect(css).toContain('.processing-sidebar__version')
    expect(css).toContain('inset -1px 0 0 rgba(168, 85, 247, 0.1)')
    expect(css).toContain('.processing-rail__fps-unit')
    expect(css).toContain('.processing-timeline__track--video-empty .processing-timeline__label')
    expect(center).toContain('processing-preview__chrome-left')
    expect(center).toContain('processing-preview__chrome-right')
    expect(css).toContain('.processing-preview--ref .processing-preview__chrome-left')
    expect(css).toContain('.processing-statusbar__item:hover')
    expect(css).toContain('background: rgba(168, 85, 247, 0.08)')
    expect(css).toContain('.processing-shell {')
    expect(css).toContain('radial-gradient(ellipse 55% 45%')
    expect(css).toContain('.processing-sidebar__logo')
    expect(css).toContain('.processing-clip--tone-violet')
    expect(css).toContain('.processing-clip--tone-cyan')
    expect(css).toContain('.processing-preview__transport-sep')
    expect(parts).toContain('processing-clip--tone-')
    expect(css).toContain('.processing-ring > span:first-child')
    expect(css).toContain('.processing-timeline__toolbar-sep')
    expect(css).toContain('.processing-clip--linked {')
    expect(css).toContain('.processing-rail__head--png {')
    expect(css).toContain('.processing-center__body {')
    expect(css).toContain('.processing-timeline__lane--audio {')
    expect(css).toContain('.processing-rail__field-label')
    expect(css).toContain('text-transform: uppercase')
    expect(css).toMatch(
      /\.processing-preview--ref \.processing-preview__overlays[\s\S]*display: none/
    )
    expect(css).toContain('.processing-statusbar__dot {')
    expect(css).toContain('.processing-sidebar__nav-block {')
    expect(css).toContain('.processing-preview__scene::before')
    expect(css).toContain('.processing-rail__section[open] .processing-rail__section-hint')
    expect(css).toContain('.processing-statusbar__tc--magenta')
    expect(data).toContain('PROCESSING_A1_TRACK_HINT')
    expect(data).toContain('НОВЫЙ СЕЗОН.vlxr')
    expect(data).toContain('PROCESSING_STATUS_PROJECT')
    expect(data).toContain("export const PROCESSING_STATUS_READY = 'Готово'")
    expect(css).toMatch(/\.processing-timeline__playhead[\s\S]*animation: none/)
    expect(data).toContain('export const V2_CLIPS: readonly ProcessingClipMock[] = []')
    expect(data).toContain('export const V3_CLIPS: readonly ProcessingClipMock[] = []')
    expect(parts).toContain('processing-timeline__lane--empty')
    expect(css).toContain('.processing-timeline__lane--empty')
    expect(css).toContain('.processing-preview__fit:hover:not(:disabled)')
    expect(css).toContain('.processing-preview__chrome-btn:hover:not(:disabled)')
    expect(data).not.toContain('PROCESSING_MEDIA_LIBRARY')
    expect(data).not.toContain('PROCESSING_STORAGE')
    expect(data).not.toContain('PROCESSING_PROJECT_FILES')
    expect(tsx).not.toContain('PROCESSING_CENTER_SUMMARY')
    expect(css).toContain('.processing-preview__scene-demo')
    expect(css).toContain('.processing-clip__film-demo')
    expect(css).toContain(
      '.processing-clip--thumb:has(.processing-clip__film--ref-demo) .processing-clip__label'
    )
    expect(css).toContain('.processing-preview--ref')
    expect(css).toContain('.processing-preview--ref .processing-preview__transport-playback')
    expect(css).toContain('.processing-preview--ref .processing-preview__volume')
    expect(css).toContain('.processing-preview--ref .processing-preview__tc-chevron')
    expect(css).toContain('.processing-preview--ref .processing-preview__transport-tools:hover')
    expect(css).toContain(
      '.processing-preview--ref .processing-preview__transport-tool:hover:not(:disabled)'
    )
    expect(css).toContain('.processing-preview--ref:hover .processing-preview__chrome')
    expect(css).toContain('.processing-preview--ref .processing-preview__zoom-chevron')
    expect(css).toContain('.processing-preview--ref .processing-chrome-glyph--search')
    expect(css).toContain('.processing-preview--ref .processing-preview__badge')
    expect(data).not.toContain('PROCESSING_RAIL_VIDEO_EXTRA')
    expect(data).not.toContain('PROCESSING_RAIL_SUMMARY')
    expect(parts).not.toContain('vn-surface-glass')
    expect(data).toContain('PROCESSING_CENTER_SUMMARY')
    expect(data).toContain('PROCESSING_STATUS_READY')
    expect(tsx).toContain('PROCESSING_STATUS_READY')
    expect(css).toContain('.processing-center__head--png')
    expect(css).toContain('.processing-rail__head--png')
    expect(css).toContain('processing-clip:hover')
    expect(css).toContain('processing-rail__section:hover')
    expect(data).toContain('PROCESSING_PREVIEW_SAVED_LABEL')
    expect(data).toContain('PROCESSING_PREVIEW_VOLUME_PERCENT')
    expect(
      readFileSync(join(process.cwd(), 'src/renderer/src/components/NeonBrandLogo.tsx'), 'utf8')
    ).toContain('processing-sidebar__brand-edition')
    expect(center).toContain('processing-preview__volume-val')
    expect(center).not.toMatch(/processing-preview__volume-val sr-only/)
    expect(css).toContain('.processing-clip--thumb::after')
    expect(css).toContain('.processing-preview__overlays')
    expect(css).toContain('.processing-rail__section--video[open]')
    expect(css).toContain('.processing-center__head--png h1')
    expect(css).toContain('.processing-timeline__ruler-ticks::after')
    expect(css).toContain('.processing-rail__preset-card strong')
    expect(css).toContain('.processing-preview__volume:hover')
    expect(css).toContain('.processing-clip--wave:hover')
    expect(css).toContain('processing-timeline__track-tools .processing-track-icon:hover')
    expect(css).toContain('prefers-reduced-motion')
    expect(data).toContain('PROCESSING_RAIL_AUDIO_FIELDS')
    expect(data).toContain('highlight: true')
    expect(tsx).toContain('ProcessingFfmpegRail')
    expect(css).toContain('processing-clip--highlight')
    expect(css).toContain('processing-clip__badge--fx')
    expect(css).toContain('.processing-clip__badge--4k')
    expect(parts).toContain("badge === '4K'")
    expect(center).toContain('processing-preview__fit-chevron')
    expect(center).not.toContain('processing-timeline__toolbar-sep')
    expect(css).toContain('.processing-timeline__toolbar-sep')
    expect(css).toContain('.processing-rail__field--slider')
    expect(parts).toContain('processing-rail__field--slider')
    expect(data).toContain('PROCESSING_GPU')
    expect(data).not.toContain('PROCESSING_STORAGE')
    expect(data).not.toContain('PROCESSING_PROJECT_FILES')
    expect(tsx).toContain('processing-sidebar__gpu-spark')
    expect(tsx).not.toContain('processing-sidebar__gpu-meters')
    expect(parts).not.toContain('processing-rail__eyebrow')
    expect(parts).not.toContain('PROCESSING_RAIL_EYEBROW')
    expect(center).toContain('processing-chrome-glyph--search')
    expect(center).toContain('processing-chrome-glyph--fullscreen')
    expect(css).toMatch(
      /\.processing-preview__scene \.processing-preview__car[\s\S]*inset 0 -4px 0 rgba\(168, 85, 247, 0\.16\)/
    )
    expect(css).toContain('.processing-preview__car::before')
    expect(css).toContain('.processing-sidebar__gpu:hover')
    expect(css).toContain('processing-preview__scanlines')
    expect(data).toContain('thumbTone:')
    expect(css).toContain('processing-clip--tone-violet')
    expect(data).toContain('PROCESSING_TIMECODE')
    expect(data).toContain('PROCESSING_TIMELINE_ZOOM_PERCENT')
    expect(center).toContain('processing-timeline__zoom-val')
    expect(center).toContain('processing-timeline__tool--active')
    expect(tsx).toContain('processing-statusbar__tc')
    expect(css).toContain('.processing-statusbar__tc')
    expect(css).toContain('.processing-timeline__track--active .processing-timeline__lane')
    expect(center).toContain('processing-preview__transport-playback')
    expect(css).toContain('--processing-rail-w')
    expect(center).not.toContain('processing-timeline__snap-pill')
    expect(tsx).toContain('processing-statusbar__item')
    expect(center).toContain('processing-preview__zoom')
    expect(center).toContain('processing-preview__zoom-chevron')
    expect(tsx).toContain('processing-statusbar__project')
    expect(parts).toContain('processing-track-icon--mute')
    expect(parts).toContain('processing-track-icon--solo')
    expect(data).toContain('PROCESSING_SYSTEM_RINGS')
    expect(tsx).toContain('PROCESSING_SYSTEM_RINGS')
    expect(tsx).toContain('--ring-pct')
    expect(css).toContain('processing-timeline__keyframe')
    expect(parts).toContain('CLIP_WAVEFORM_BAR_COUNT')
    expect(chrome).toContain('requestMinimize')
    expect(chrome).toContain('requestClose')
  })

  it('bootstrap defaults to ref.1 route', () => {
    const bootstrap = readFileSync(
      join(process.cwd(), 'src/renderer/src/app-neon-bootstrap.tsx'),
      'utf8'
    )
    expect(bootstrap).toContain("return 'ref1'")
    expect(bootstrap).toContain('ProcessingScreen')
  })
})
