import { useId, useRef, useState } from 'react'
import type { ResolvedAppTheme } from '../../shared/settings-contract'
import type { RestoredSourceInfo } from '../../shared/preview-dialog-contract'
import type { MediaProbeSuccess } from '../../shared/ffprobe-contract'
import { useDownloadsWindowUiPanels } from './use-downloads-window-ui-panels'
import { useMainWindowUiPanels } from './use-main-window-ui-panels'
import { useEditorExportSettings } from './use-editor-export-settings'
import { useAppProcessingHistory } from './use-app-processing-history'
import { useDownloadsWorkspace } from './use-downloads-workspace'
import { type EnginePathsDraft, type EngineSummary } from './app-engines-ui'
import type { WorkspaceTab } from './app-terminal-hint-ui'
import { type DownloadsQueueRowView, type DownloadsStatusFilter } from './downloads-queue-view'

/** Return type: `AppCompositionState` (declared below). */
// eslint-disable-next-line @typescript-eslint/explicit-function-return-type -- inferred object matches AppCompositionState
export function useAppCompositionState() {
  const [workspaceTab, setWorkspaceTab] = useState<WorkspaceTab>('editor')
  const [theme, setTheme] = useState<ResolvedAppTheme>('dark')
  const [engineSummary, setEngineSummary] = useState<EngineSummary>('checking')
  const [enginesOfferDownload, setEnginesOfferDownload] = useState(false)
  const [engineDownloadBusy, setEngineDownloadBusy] = useState(false)
  const [enginePathsOpen, setEnginePathsOpen] = useState(false)
  /** Сброс дерева после `applyPersistedUiLocale` — строки из `ui-text` читают `getUiLocale()` из модуля. */
  const [uiLocaleRenderTick, setUiLocaleRenderTick] = useState(0)
  const [knowledgeOpen, setKnowledgeOpen] = useState(false)
  const [knowledgeInitialSlug, setKnowledgeInitialSlug] = useState<string | null>(null)
  const [aboutOpen, setAboutOpen] = useState(false)
  const [aboutInfo, setAboutInfo] = useState<Awaited<
    ReturnType<typeof window.fluxalloy.about.getInfo>
  > | null>(null)
  const [enginePathsDraft, setEnginePathsDraft] = useState<EnginePathsDraft>({
    ffmpeg: '',
    ffprobe: '',
    'yt-dlp': ''
  })
  const [enginePathsSaving, setEnginePathsSaving] = useState(false)
  /** Подстрочное сообщение статусбара: прогресс загрузки движков, ошибки DnD и т.п. */
  const [statusHint, setStatusHint] = useState<string | null>(null)
  const [preview, setPreview] = useState<RestoredSourceInfo | null>(null)
  const [previewBlobUrl, setPreviewBlobUrl] = useState<string | null>(null)
  const [probeInfo, setProbeInfo] = useState<MediaProbeSuccess | null>(null)
  const [probePending, setProbePending] = useState(false)
  const [downloadsUrl, setDownloadsUrl] = useState('')
  const [downloadsRows, setDownloadsRows] = useState<DownloadsQueueRowView[]>([])
  const [downloadsStatusFilter, setDownloadsStatusFilter] = useState<DownloadsStatusFilter>('all')
  const {
    downloadsOptions,
    setDownloadsOptions,
    downloadsOptionsBusy,
    downloadsExpertHintFilter,
    setDownloadsExpertHintFilter,
    downloadsHistory,
    setDownloadsHistory,
    downloadsHistoryBusy,
    downloadsHistoryOutcomeFilter,
    setDownloadsHistoryOutcomeFilter,
    downloadsHistoryWeeklySummary,
    downloadsLogLines,
    setDownloadsLogLines,
    downloadsLogTargetRowId,
    setDownloadsLogTargetRowId,
    downloadsOutputDirectory,
    setDownloadsOutputDirectory,
    visibleDownloadsHistory,
    ytdlpCommandHintsFilteredByCategory,
    refreshDownloadsOptions,
    applyDownloadsOptionsPatch,
    appendDownloadsExtraArgsToken,
    refreshDownloadsHistory,
    exportVisibleDownloadsHistory,
    refreshDownloadsOutputDirectory
  } = useDownloadsWorkspace({ setStatusHint })
  const {
    processingHistory,
    setProcessingHistory,
    processingHistoryBusy,
    processingHistoryFilter,
    processingHistoryWeeklySummary,
    setProcessingHistoryWeeklySummary,
    refreshProcessingHistory,
    applyProcessingHistoryFilter,
    exportVisibleProcessingHistory
  } = useAppProcessingHistory({ setStatusHint })
  const {
    downloadsEmbeddedHistoryOpen,
    downloadsEmbeddedLogOpen,
    downloadsRailPanels,
    hydrateDownloadsWindowUiPanels,
    persistDownloadsEmbeddedHistoryOpen,
    persistDownloadsEmbeddedLogOpen,
    persistDownloadsRailPanelToggle
  } = useDownloadsWindowUiPanels()
  /** Совпадает с `max-width: 1100px` в `main.css` для вкладки «Загрузки». */
  const [downloadsNarrowLayout, setDownloadsNarrowLayout] = useState(false)
  const downloadsMainUrlFieldId = useId()
  const [engineVersionsLine, setEngineVersionsLine] = useState('')
  const [exportBusy, setExportBusy] = useState(false)
  const [exportCancelBusy, setExportCancelBusy] = useState(false)
  const {
    exportEncodePreset,
    setExportEncodePreset,
    exportVideoCodec,
    setExportVideoCodec,
    hwEncoderProbe,
    exportContainer,
    setExportContainer,
    exportCrf,
    setExportCrf,
    exportVideoBitrate,
    setExportVideoBitrate,
    exportAudioMode,
    setExportAudioMode,
    exportAudioBitrate,
    setExportAudioBitrate,
    exportFps,
    setExportFps,
    exportVideoTransform,
    setExportVideoTransform,
    exportCropPreset,
    setExportCropPreset,
    exportScalePreset,
    setExportScalePreset,
    exportTwoPass,
    setExportTwoPass,
    exportEconomyMode,
    setExportEconomyMode,
    exportHwDecode,
    setExportHwDecode,
    exportExtraArgsLine,
    setExportExtraArgsLine,
    editorUrlPasteBehavior,
    setEditorUrlPasteBehavior,
    batchOutputSuffix,
    setBatchOutputSuffix,
    batchOutputDirectory,
    setBatchOutputDirectory,
    exportAudioGainDb,
    setExportAudioGainDb,
    exportStripMetadata,
    setExportStripMetadata,
    exportStripChapters,
    setExportStripChapters,
    exportSubtitleMode,
    setExportSubtitleMode,
    exportVideoDeinterlace,
    setExportVideoDeinterlace,
    exportVideoDenoise,
    setExportVideoDenoise,
    exportVideoDeband,
    setExportVideoDeband,
    exportVideoHisteq,
    setExportVideoHisteq,
    exportVideoLut3d,
    setExportVideoLut3d,
    lutCubePathForPreview,
    exportVideoSharpen,
    setExportVideoSharpen,
    exportVideoEqPreset,
    setExportVideoEqPreset,
    exportVideoHue,
    setExportVideoHue,
    exportVideoGrain,
    setExportVideoGrain,
    exportVideoVignette,
    setExportVideoVignette,
    exportVideoBlur,
    setExportVideoBlur,
    exportAudioNormalize,
    setExportAudioNormalize,
    exportUserPresets,
    setExportUserPresets,
    selectedUserPresetId,
    setSelectedUserPresetId,
    selectedExportUserPreset,
    exportPresetNameDialog,
    setExportPresetNameDialog,
    exportPresetSaving,
    lastExportPath,
    setLastExportPath,
    lastSnapshotPath,
    setLastSnapshotPath,
    snapshotFormat,
    setSnapshotFormat,
    snapshotBusy,
    setSnapshotBusy,
    ffmpegExportSelectOptions,
    exportVideoCodecResolvedForPreview,
    exportExtraArgsParsed,
    exportHwaccelDecodeForPreview,
    exportCodecStatusbarLabel,
    refetchHwEncoders,
    hydrateExportFieldsFromSettings,
    bumpManualExportEdit,
    buildCurrentFfmpegExportOverrides,
    handleSaveExportUserPreset,
    handleDeleteExportUserPreset,
    handleRenameExportUserPreset,
    handleSubmitExportPresetName,
    handleOverwriteExportUserPreset
  } = useEditorExportSettings({ setStatusHint })
  const videoRef = useRef<HTMLVideoElement>(null)
  const { panelOpen, hydrateMainWindowUiPanels, persistMainWindowUiPanelToggle } =
    useMainWindowUiPanels()
  /** Стек видео+транспорт+таймлайн: цель fullscreen по референсу v0. */
  const previewStackRef = useRef<HTMLDivElement>(null)
  /** §6 / узкая ширина: `scrollIntoView` к панели настроек yt-dlp под очередью. */
  const downloadsSettingsRailRef = useRef<HTMLElement | null>(null)
  return {
    aboutInfo,
    aboutOpen,
    appendDownloadsExtraArgsToken,
    applyDownloadsOptionsPatch,
    applyProcessingHistoryFilter,
    batchOutputDirectory,
    batchOutputSuffix,
    buildCurrentFfmpegExportOverrides,
    bumpManualExportEdit,
    downloadsEmbeddedHistoryOpen,
    downloadsEmbeddedLogOpen,
    downloadsExpertHintFilter,
    downloadsHistory,
    downloadsHistoryBusy,
    downloadsHistoryOutcomeFilter,
    downloadsHistoryWeeklySummary,
    downloadsLogLines,
    downloadsLogTargetRowId,
    downloadsMainUrlFieldId,
    downloadsNarrowLayout,
    downloadsOptions,
    downloadsOptionsBusy,
    downloadsOutputDirectory,
    downloadsRailPanels,
    downloadsRows,
    downloadsSettingsRailRef,
    downloadsStatusFilter,
    downloadsUrl,
    editorUrlPasteBehavior,
    engineDownloadBusy,
    enginePathsDraft,
    enginePathsOpen,
    enginePathsSaving,
    engineSummary,
    engineVersionsLine,
    enginesOfferDownload,
    exportAudioBitrate,
    exportAudioGainDb,
    exportAudioMode,
    exportAudioNormalize,
    exportBusy,
    exportCancelBusy,
    exportCodecStatusbarLabel,
    exportContainer,
    exportCrf,
    exportCropPreset,
    exportEconomyMode,
    exportEncodePreset,
    exportExtraArgsLine,
    exportExtraArgsParsed,
    exportFps,
    exportHwDecode,
    exportHwaccelDecodeForPreview,
    exportPresetNameDialog,
    exportPresetSaving,
    exportScalePreset,
    exportStripChapters,
    exportStripMetadata,
    exportSubtitleMode,
    exportTwoPass,
    exportUserPresets,
    exportVideoBitrate,
    exportVideoBlur,
    exportVideoCodec,
    exportVideoCodecResolvedForPreview,
    exportVideoDeband,
    exportVideoDeinterlace,
    exportVideoDenoise,
    exportVideoEqPreset,
    exportVideoGrain,
    exportVideoHisteq,
    exportVideoHue,
    exportVideoLut3d,
    exportVideoSharpen,
    exportVideoTransform,
    exportVideoVignette,
    exportVisibleDownloadsHistory,
    exportVisibleProcessingHistory,
    ffmpegExportSelectOptions,
    handleDeleteExportUserPreset,
    handleOverwriteExportUserPreset,
    handleRenameExportUserPreset,
    handleSaveExportUserPreset,
    handleSubmitExportPresetName,
    hwEncoderProbe,
    hydrateDownloadsWindowUiPanels,
    hydrateExportFieldsFromSettings,
    hydrateMainWindowUiPanels,
    knowledgeInitialSlug,
    knowledgeOpen,
    lastExportPath,
    lastSnapshotPath,
    lutCubePathForPreview,
    panelOpen,
    persistDownloadsEmbeddedHistoryOpen,
    persistDownloadsEmbeddedLogOpen,
    persistDownloadsRailPanelToggle,
    persistMainWindowUiPanelToggle,
    preview,
    previewBlobUrl,
    previewStackRef,
    probeInfo,
    probePending,
    processingHistory,
    processingHistoryBusy,
    processingHistoryFilter,
    processingHistoryWeeklySummary,
    refetchHwEncoders,
    refreshDownloadsHistory,
    refreshDownloadsOptions,
    refreshDownloadsOutputDirectory,
    refreshProcessingHistory,
    selectedExportUserPreset,
    selectedUserPresetId,
    setAboutInfo,
    setAboutOpen,
    setBatchOutputDirectory,
    setBatchOutputSuffix,
    setDownloadsExpertHintFilter,
    setDownloadsHistory,
    setDownloadsHistoryOutcomeFilter,
    setDownloadsLogLines,
    setDownloadsLogTargetRowId,
    setDownloadsNarrowLayout,
    setDownloadsOptions,
    setDownloadsOutputDirectory,
    setDownloadsRows,
    setDownloadsStatusFilter,
    setDownloadsUrl,
    setEditorUrlPasteBehavior,
    setEngineDownloadBusy,
    setEnginePathsDraft,
    setEnginePathsOpen,
    setEnginePathsSaving,
    setEngineSummary,
    setEngineVersionsLine,
    setEnginesOfferDownload,
    setExportAudioBitrate,
    setExportAudioGainDb,
    setExportAudioMode,
    setExportAudioNormalize,
    setExportBusy,
    setExportCancelBusy,
    setExportContainer,
    setExportCrf,
    setExportCropPreset,
    setExportEconomyMode,
    setExportEncodePreset,
    setExportExtraArgsLine,
    setExportFps,
    setExportHwDecode,
    setExportPresetNameDialog,
    setExportScalePreset,
    setExportStripChapters,
    setExportStripMetadata,
    setExportSubtitleMode,
    setExportTwoPass,
    setExportUserPresets,
    setExportVideoBitrate,
    setExportVideoBlur,
    setExportVideoCodec,
    setExportVideoDeband,
    setExportVideoDeinterlace,
    setExportVideoDenoise,
    setExportVideoEqPreset,
    setExportVideoGrain,
    setExportVideoHisteq,
    setExportVideoHue,
    setExportVideoLut3d,
    setExportVideoSharpen,
    setExportVideoTransform,
    setExportVideoVignette,
    setKnowledgeInitialSlug,
    setKnowledgeOpen,
    setLastExportPath,
    setLastSnapshotPath,
    setPreview,
    setPreviewBlobUrl,
    setProbeInfo,
    setProbePending,
    setProcessingHistory,
    setProcessingHistoryWeeklySummary,
    setSelectedUserPresetId,
    setSnapshotBusy,
    setSnapshotFormat,
    setStatusHint,
    setTheme,
    setUiLocaleRenderTick,
    setWorkspaceTab,
    snapshotBusy,
    snapshotFormat,
    statusHint,
    theme,
    uiLocaleRenderTick,
    videoRef,
    visibleDownloadsHistory,
    workspaceTab,
    ytdlpCommandHintsFilteredByCategory
  }
}

export type AppCompositionState = ReturnType<typeof useAppCompositionState>
