import type { AppShellPropsInputCtx } from './use-app-shell-props-input-workspace-types'
import type { UseAppWorkspaceMainPropsInput } from './use-app-workspace-main-props'

export function buildAppShellPropsInputWorkspaceTerminalDownloads(
  ctx: AppShellPropsInputCtx
): Pick<UseAppWorkspaceMainPropsInput, 'terminal' | 'downloads'> {
  const {
    terminalBusy,
    terminalLine,
    setTerminalLine,
    terminalCommandInputId,
    terminalInlineSuggestions,
    terminalSuggestFocus,
    setTerminalSuggestFocus,
    terminalSuggestActiveIndex,
    setTerminalSuggestIndex,
    terminalSuggestBlurTimeoutRef,
    currentSourcePath,
    runTerminalLine,
    recallTerminalCommand,
    applyTerminalSuggest,
    appendTerminalToken,
    terminalHistory,
    copyTerminalOutputLine,
    terminalHintsSearchFieldId,
    terminalHintFilter,
    setTerminalHintFilter,
    visibleTerminalHints,
    downloadsOptionsBusy,
    downloadsHistoryBusy,
    downloadsUrl,
    setDownloadsUrl,
    downloadsMainUrlFieldId,
    downloadsNarrowLayout,
    downloadsStats,
    downloadsStatusFilter,
    setDownloadsStatusFilter,
    downloadsStatusFilterChips,
    downloadsRows,
    visibleDownloadsRows,
    setStatusHint,
    downloadsEmbeddedHistoryOpen,
    persistDownloadsEmbeddedHistoryOpen,
    visibleDownloadsHistory,
    downloadsHistory,
    downloadsHistoryOutcomeFilter,
    setDownloadsHistoryOutcomeFilter,
    downloadsHistoryWeeklySummary,
    refreshDownloadsHistory,
    setDownloadsHistory,
    exportVisibleDownloadsHistory,
    downloadsEmbeddedLogOpen,
    persistDownloadsEmbeddedLogOpen,
    downloadsLogTargetRowId,
    downloadsLogLines,
    setDownloadsLogLines,
    setDownloadsLogTargetRowId,
    downloadsOptions,
    setDownloadsOptions,
    downloadsRailPanels,
    handleDownloadsRailSectionToggle,
    applyDownloadsOptionsPatch,
    downloadsOutputDirectory,
    setDownloadsOutputDirectory,
    refreshDownloadsOutputDirectory,
    downloadsExpertHintFilter,
    setDownloadsExpertHintFilter,
    ytdlpCommandHintsFilteredByCategory,
    appendDownloadsExtraArgsToken,
    refreshDownloadsOptions,
    setWorkspaceTab,
    handleAddDownloadsFromMain,
    handleBatchAddDownloadsDone
  } = ctx

  return {
    terminal: {
      terminalBusy,
      terminalLine,
      setTerminalLine,
      terminalCommandInputId,
      terminalInlineSuggestions,
      terminalSuggestFocus,
      setTerminalSuggestFocus,
      terminalSuggestActiveIndex,
      setTerminalSuggestIndex,
      terminalSuggestBlurTimeoutRef,
      currentSourcePath,
      runTerminalLine,
      recallTerminalCommand,
      applyTerminalSuggest,
      appendTerminalToken,
      terminalHistory,
      copyTerminalOutputLine,
      terminalHintsSearchFieldId,
      terminalHintFilter,
      setTerminalHintFilter,
      visibleTerminalHints
    },
    downloads: {
      main: {
        downloadsOptionsBusy,
        downloadsHistoryBusy,
        downloadsUrl,
        setDownloadsUrl,
        downloadsMainUrlFieldId,
        downloadsNarrowLayout,
        downloadsStats,
        downloadsStatusFilter,
        setDownloadsStatusFilter,
        downloadsStatusFilterChips,
        downloadsRows,
        visibleDownloadsRows,
        setStatusHint,
        downloadsEmbeddedHistoryOpen,
        persistDownloadsEmbeddedHistoryOpen,
        visibleDownloadsHistory,
        downloadsHistoryCount: downloadsHistory.length,
        downloadsHistoryOutcomeFilter,
        setDownloadsHistoryOutcomeFilter,
        downloadsHistoryWeeklySummary: downloadsHistoryWeeklySummary ?? {
          since: 0,
          until: 0,
          total: 0,
          success: 0,
          error: 0,
          cancelled: 0
        },
        refreshDownloadsHistory,
        setDownloadsHistory,
        exportVisibleDownloadsHistory,
        downloadsEmbeddedLogOpen,
        persistDownloadsEmbeddedLogOpen,
        downloadsLogTargetRowId,
        downloadsLogLines,
        setDownloadsLogLines,
        setDownloadsLogTargetRowId
      },
      settings: {
        downloadsOptionsBusy,
        downloadsHistoryBusy,
        downloadsOptions,
        setDownloadsOptions,
        downloadsRailPanels,
        onRailSectionToggle: handleDownloadsRailSectionToggle,
        applyDownloadsOptionsPatch,
        downloadsOutputDirectory,
        setDownloadsOutputDirectory,
        refreshDownloadsOutputDirectory,
        setStatusHint,
        downloadsExpertHintFilter,
        setDownloadsExpertHintFilter,
        ytdlpCommandHintsFilteredByCategory,
        appendDownloadsExtraArgsToken,
        refreshDownloadsOptions
      },
      setWorkspaceTab,
      handleAddDownloadsFromMain,
      handleBatchAddDownloadsDone
    }
  }
}
