import { useCallback, useMemo } from 'react'
import type { SyntheticEvent } from 'react'
import { uiText } from './locales/ui-text'
import { type DownloadsRailPanelKey } from './use-downloads-window-ui-panels'
import { useEditorExportPipeline } from './use-editor-export-pipeline'
import { useAppMainWindowEffects } from './use-app-main-window-effects'
import { useAppPreviewWorkspace } from './use-app-preview-workspace'
import { useAppToolbarEngineActions } from './use-app-toolbar-engine-actions'
import { useFfmpegExportBatch } from './use-ffmpeg-export-batch'
import { useTerminalWorkspace } from './use-terminal-workspace'
import { useDownloadsUrlActions } from './use-downloads-url-actions'
import {
  type DownloadsStatusFilter,
  downloadsRowMatchesStatus,
  summarizeDownloadsRows
} from './downloads-queue-view'
import type { UseAppShellPropsInput } from './use-app-shell-props'
import type { AppCompositionState } from './use-app-composition-state'

export function useAppShellPropsInput(state: AppCompositionState): UseAppShellPropsInput {
  const {
    aboutInfo,
    aboutOpen,
    appendDownloadsExtraArgsToken,
    applyDownloadsOptionsPatch,
    applyProcessingHistoryFilter,
    batchOutputDirectory,
    batchOutputSuffix,
    buildCurrentFfmpegExportOverrides,
    bumpManualExportEdit,
    downloadsEmbeddedHistoryOpen,
    downloadsEmbeddedLogOpen,
    downloadsExpertHintFilter,
    downloadsHistory,
    downloadsHistoryBusy,
    downloadsHistoryOutcomeFilter,
    downloadsHistoryWeeklySummary,
    downloadsLogLines,
    downloadsLogTargetRowId,
    downloadsMainUrlFieldId,
    downloadsNarrowLayout,
    downloadsOptions,
    downloadsOptionsBusy,
    downloadsOutputDirectory,
    downloadsRailPanels,
    downloadsRows,
    downloadsSettingsRailRef,
    downloadsStatusFilter,
    downloadsUrl,
    editorUrlPasteBehavior,
    engineDownloadBusy,
    enginePathsDraft,
    enginePathsOpen,
    enginePathsSaving,
    engineSummary,
    engineVersionsLine,
    enginesOfferDownload,
    exportAudioBitrate,
    exportAudioGainDb,
    exportAudioMode,
    exportAudioNormalize,
    exportBusy,
    exportCancelBusy,
    exportCodecStatusbarLabel,
    exportContainer,
    exportCrf,
    exportCropPreset,
    exportEconomyMode,
    exportEncodePreset,
    exportExtraArgsLine,
    exportExtraArgsParsed,
    exportFps,
    exportHwDecode,
    exportHwaccelDecodeForPreview,
    exportPresetNameDialog,
    exportPresetSaving,
    exportScalePreset,
    exportStripChapters,
    exportStripMetadata,
    exportSubtitleMode,
    exportTwoPass,
    exportUserPresets,
    exportVideoBitrate,
    exportVideoBlur,
    exportVideoCodec,
    exportVideoCodecResolvedForPreview,
    exportVideoDeband,
    exportVideoDeinterlace,
    exportVideoDenoise,
    exportVideoEqPreset,
    exportVideoGrain,
    exportVideoHisteq,
    exportVideoHue,
    exportVideoLut3d,
    exportVideoSharpen,
    exportVideoTransform,
    exportVideoVignette,
    exportVisibleDownloadsHistory,
    exportVisibleProcessingHistory,
    ffmpegExportSelectOptions,
    handleDeleteExportUserPreset,
    handleOverwriteExportUserPreset,
    handleRenameExportUserPreset,
    handleSaveExportUserPreset,
    handleSubmitExportPresetName,
    hwEncoderProbe,
    hydrateDownloadsWindowUiPanels,
    hydrateExportFieldsFromSettings,
    hydrateMainWindowUiPanels,
    knowledgeInitialSlug,
    knowledgeOpen,
    lastExportPath,
    lastSnapshotPath,
    lutCubePathForPreview,
    panelOpen,
    persistDownloadsEmbeddedHistoryOpen,
    persistDownloadsEmbeddedLogOpen,
    persistDownloadsRailPanelToggle,
    persistMainWindowUiPanelToggle,
    preview,
    previewBlobUrl,
    previewStackRef,
    probeInfo,
    probePending,
    processingHistory,
    processingHistoryBusy,
    processingHistoryFilter,
    processingHistoryWeeklySummary,
    refetchHwEncoders,
    refreshDownloadsHistory,
    refreshDownloadsOptions,
    refreshDownloadsOutputDirectory,
    refreshProcessingHistory,
    selectedExportUserPreset,
    selectedUserPresetId,
    setAboutInfo,
    setAboutOpen,
    setBatchOutputDirectory,
    setBatchOutputSuffix,
    setDownloadsExpertHintFilter,
    setDownloadsHistory,
    setDownloadsHistoryOutcomeFilter,
    setDownloadsLogLines,
    setDownloadsLogTargetRowId,
    setDownloadsNarrowLayout,
    setDownloadsOptions,
    setDownloadsOutputDirectory,
    setDownloadsRows,
    setDownloadsStatusFilter,
    setDownloadsUrl,
    setEditorUrlPasteBehavior,
    setEngineDownloadBusy,
    setEnginePathsDraft,
    setEnginePathsOpen,
    setEnginePathsSaving,
    setEngineSummary,
    setEngineVersionsLine,
    setEnginesOfferDownload,
    setExportAudioBitrate,
    setExportAudioGainDb,
    setExportAudioMode,
    setExportAudioNormalize,
    setExportBusy,
    setExportCancelBusy,
    setExportContainer,
    setExportCrf,
    setExportCropPreset,
    setExportEconomyMode,
    setExportEncodePreset,
    setExportExtraArgsLine,
    setExportFps,
    setExportHwDecode,
    setExportPresetNameDialog,
    setExportScalePreset,
    setExportStripChapters,
    setExportStripMetadata,
    setExportSubtitleMode,
    setExportTwoPass,
    setExportUserPresets,
    setExportVideoBitrate,
    setExportVideoBlur,
    setExportVideoCodec,
    setExportVideoDeband,
    setExportVideoDeinterlace,
    setExportVideoDenoise,
    setExportVideoEqPreset,
    setExportVideoGrain,
    setExportVideoHisteq,
    setExportVideoHue,
    setExportVideoLut3d,
    setExportVideoSharpen,
    setExportVideoTransform,
    setExportVideoVignette,
    setKnowledgeInitialSlug,
    setKnowledgeOpen,
    setLastExportPath,
    setLastSnapshotPath,
    setPreview,
    setPreviewBlobUrl,
    setProbeInfo,
    setProbePending,
    setProcessingHistory,
    setProcessingHistoryWeeklySummary,
    setSelectedUserPresetId,
    setSnapshotBusy,
    setSnapshotFormat,
    setStatusHint,
    setTheme,
    setUiLocaleRenderTick,
    setWorkspaceTab,
    snapshotBusy,
    snapshotFormat,
    statusHint,
    theme,
    uiLocaleRenderTick,
    videoRef,
    visibleDownloadsHistory,
    workspaceTab,
    ytdlpCommandHintsFilteredByCategory
  } = state

  const {
    trimSnapshotRef,
    trimRange,
    currentSourcePath,
    previewPlaybackUrl,
    applyPreview,
    handlePreviewVideoError,
    handlePreviewVideoLoaded,
    onTrimRangeSnapshot,
    jumpToTrimExport,
    handlePreviewDrop
  } = useAppPreviewWorkspace({
    preview,
    setPreview,
    previewBlobUrl,
    setPreviewBlobUrl,
    setProbeInfo,
    setStatusHint,
    setWorkspaceTab,
    persistMainWindowUiPanelToggle,
    editorUrlPasteBehavior,
    setDownloadsUrl
  })

  const {
    terminalLine,
    setTerminalLine,
    terminalBusy,
    terminalHintFilter,
    setTerminalHintFilter,
    terminalHistory,
    terminalSuggestFocus,
    setTerminalSuggestFocus,
    terminalSuggestBlurTimeoutRef,
    terminalHintsSearchFieldId,
    terminalCommandInputId,
    visibleTerminalHints,
    terminalInlineSuggestions,
    terminalSuggestActiveIndex,
    setTerminalSuggestIndex,
    appendTerminalToken,
    applyTerminalSuggest,
    runTerminalLine,
    copyTerminalOutputLine
  } = useTerminalWorkspace({
    workspaceTab,
    currentSourcePath,
    setStatusHint
  })

  const downloadsStats = useMemo(() => summarizeDownloadsRows(downloadsRows), [downloadsRows])
  const visibleDownloadsRows = useMemo(
    () => downloadsRows.filter((row) => downloadsRowMatchesStatus(row, downloadsStatusFilter)),
    [downloadsRows, downloadsStatusFilter]
  )
  const downloadsStatusFilterChips = useMemo(
    (): Array<{ id: DownloadsStatusFilter; label: string }> => [
      { id: 'all', label: uiText('downloadsQueueFilterAll') },
      { id: 'running', label: uiText('downloadsQueueFilterRunning') },
      { id: 'done', label: uiText('downloadsQueueFilterDone') },
      { id: 'error', label: uiText('downloadsQueueFilterError') },
      { id: 'cancelled', label: uiText('downloadsQueueFilterCancelled') }
    ],
    []
  )

  const handleDownloadsRailSectionToggle = useCallback(
    (key: DownloadsRailPanelKey) => {
      return (e: SyntheticEvent<HTMLDetailsElement>): void => {
        const open = e.currentTarget.open
        persistDownloadsRailPanelToggle(key, open)
      }
    },
    [persistDownloadsRailPanelToggle]
  )

  const {
    handleAddDownloadsFromMain,
    handleQuickYtdlpEnqueueLines,
    handleDownloadFirstUrlOpenInEditor
  } = useDownloadsUrlActions({
    downloadsUrl,
    setDownloadsUrl,
    setWorkspaceTab,
    setStatusHint
  })

  const { refreshEngineUi } = useAppMainWindowEffects({
    trimSnapshotRef,
    currentSourcePath,
    setDownloadsRows,
    setTheme,
    setUiLocaleRenderTick,
    hydrateExportFieldsFromSettings,
    hydrateMainWindowUiPanels,
    hydrateDownloadsWindowUiPanels,
    setExportUserPresets,
    setSnapshotFormat,
    refetchHwEncoders,
    applyPreview,
    previewPath: currentSourcePath,
    previewMediaUrl: preview?.mediaUrl,
    setPreviewBlobUrl,
    setProbeInfo,
    setProbePending,
    setStatusHint,
    setEngineSummary,
    setEngineVersionsLine,
    setEnginesOfferDownload,
    engineSummary,
    enginePathsOpen,
    setEnginePathsDraft,
    setEnginePathsOpen,
    setAboutInfo,
    setAboutOpen,
    editorUrlPasteBehavior,
    setWorkspaceTab,
    setDownloadsUrl,
    setDownloadsNarrowLayout
  })

  const {
    batchSnapshot,
    batchDragRowId,
    setBatchDragRowId,
    batchExportBusy,
    handleBatchOpenOutput,
    handleBatchOpenInput,
    handleBatchPickFiles,
    handleBatchPickFolder,
    handleBatchPickOutputFolder,
    handleBatchClearOutputDirectory,
    handleBatchRevealSharedOutputFolder,
    handleBatchDropFiles,
    handleBatchStart,
    handleBatchCancel,
    handleBatchRetryFailed,
    handleBatchClearCompleted,
    handleBatchAddCurrentPreview,
    handleBatchAddDownloadsDone,
    handleBatchRetryFailedAndStart,
    handleBatchCopyInputPaths,
    handleBatchCopyOutputPaths,
    handleBatchCopyRowPath,
    handleBatchSaveReport,
    handleBatchRemoveWaiting,
    reportBatchPathsAdded
  } = useFfmpegExportBatch({
    setStatusHint,
    setWorkspaceTab,
    buildExportOverrides: buildCurrentFfmpegExportOverrides,
    previewPath: preview?.path,
    exportBusy,
    setBatchOutputDirectory,
    onBatchRunFinished: refreshProcessingHistory
  })

  const {
    handleSnapshot,
    handleExport,
    handleCancelExport,
    handleOpenLastExport,
    handleCopyLastExportPath,
    handleOpenLastSnapshot,
    handleCopyLastSnapshotPath,
    exportPreview,
    exportPreviewCommand,
    exportPreviewHint,
    handleCopyExportPreview
  } = useEditorExportPipeline({
    setStatusHint,
    preview,
    probeInfo,
    trimRange,
    trimSnapshotRef,
    videoRef,
    exportBusy,
    setExportBusy,
    exportCancelBusy,
    setExportCancelBusy,
    batchExportBusy,
    snapshotBusy,
    setSnapshotBusy,
    refreshProcessingHistory,
    buildCurrentFfmpegExportOverrides,
    exportContainer,
    exportEncodePreset,
    exportVideoCodecResolvedForPreview,
    exportCrf,
    exportVideoBitrate,
    exportAudioMode,
    exportAudioBitrate,
    exportFps,
    exportScalePreset,
    exportVideoTransform,
    exportCropPreset,
    exportTwoPass,
    exportEconomyMode,
    exportHwaccelDecodeForPreview,
    exportExtraArgsParsed,
    exportAudioGainDb,
    exportStripMetadata,
    exportStripChapters,
    exportSubtitleMode,
    exportVideoDeinterlace,
    exportVideoDenoise,
    exportVideoDeband,
    exportVideoHisteq,
    lutCubePathForPreview,
    exportVideoSharpen,
    exportVideoEqPreset,
    exportVideoHue,
    exportVideoGrain,
    exportVideoVignette,
    exportVideoBlur,
    exportAudioNormalize,
    lastExportPath,
    setLastExportPath,
    lastSnapshotPath,
    setLastSnapshotPath
  })

  const {
    toggleTheme,
    handleUiLocaleToggle,
    handleOpenToolbar,
    handleOpenVideoFolderToolbar,
    handleEnginesDownload,
    handleClearDownloadedEngines,
    handleSaveEnginePaths,
    handlePickEngine
  } = useAppToolbarEngineActions({
    applyPreview,
    setStatusHint,
    setUiLocaleRenderTick,
    refreshEngineUi,
    setEngineDownloadBusy,
    enginePathsDraft,
    setEnginePathsDraft,
    setEnginePathsOpen,
    setEnginePathsSaving
  })
  return {
    workspace: {
      shell: {
        workspaceTab,
        panelOpen,
        persistMainWindowUiPanelToggle,
        downloadsSettingsRailRef
      },
      knowledge: {
        setKnowledgeInitialSlug,
        setKnowledgeOpen
      },
      busy: {
        engineDownloadBusy,
        exportBusy,
        snapshotBusy,
        probePending,
        exportCancelBusy,
        batchExportBusy,
        downloadsOptionsBusy,
        downloadsHistoryBusy
      },
      editorQuick: {
        downloadsUrl,
        setDownloadsUrl,
        editorUrlPasteBehavior,
        setEditorUrlPasteBehavior,
        handleQuickYtdlpEnqueueLines,
        handleDownloadFirstUrlOpenInEditor
      },
      editorBatch: {
        batchExportBusy,
        batchSnapshot,
        batchOutputSuffix,
        setBatchOutputSuffix,
        batchOutputDirectory,
        batchDragRowId,
        setBatchDragRowId,
        previewPath: preview?.path,
        setStatusHint,
        handleBatchDropFiles,
        handleBatchPickOutputFolder,
        handleBatchRevealSharedOutputFolder,
        handleBatchClearOutputDirectory,
        handleBatchPickFiles,
        handleBatchPickFolder,
        handleBatchAddCurrentPreview,
        handleBatchAddDownloadsDone,
        handleBatchStart,
        handleBatchCancel,
        handleBatchRetryFailed,
        handleBatchRetryFailedAndStart,
        handleBatchClearCompleted,
        handleBatchCopyInputPaths,
        handleBatchCopyOutputPaths,
        handleBatchSaveReport,
        handleBatchRemoveWaiting,
        handleBatchOpenOutput,
        handleBatchOpenInput,
        handleBatchCopyRowPath
      },
      editorPreview: {
        preview,
        previewPlaybackUrl,
        previewStackRef,
        videoRef,
        probeInfo,
        probePending,
        exportBusy,
        snapshotBusy,
        handlePreviewDrop,
        handlePreviewVideoLoaded,
        handlePreviewVideoError,
        onTrimRangeSnapshot,
        jumpToTrimExport,
        handleExport,
        handleSnapshot
      },
      editorFfmpeg: {
        setStatusHint,
        exportBusy,
        exportCancelBusy,
        snapshotBusy,
        probePending,
        exportEncodePreset,
        setExportEncodePreset,
        exportVideoCodec,
        setExportVideoCodec,
        exportContainer,
        setExportContainer,
        exportCrf,
        setExportCrf,
        exportVideoBitrate,
        setExportVideoBitrate,
        exportAudioMode,
        setExportAudioMode,
        exportAudioBitrate,
        setExportAudioBitrate,
        exportFps,
        setExportFps,
        exportVideoTransform,
        setExportVideoTransform,
        exportCropPreset,
        setExportCropPreset,
        exportScalePreset,
        setExportScalePreset,
        exportTwoPass,
        setExportTwoPass,
        exportEconomyMode,
        setExportEconomyMode,
        exportHwDecode,
        setExportHwDecode,
        exportExtraArgsLine,
        setExportExtraArgsLine,
        exportAudioGainDb,
        setExportAudioGainDb,
        exportStripMetadata,
        setExportStripMetadata,
        exportStripChapters,
        setExportStripChapters,
        exportSubtitleMode,
        setExportSubtitleMode,
        exportVideoDeinterlace,
        setExportVideoDeinterlace,
        exportVideoDenoise,
        setExportVideoDenoise,
        exportVideoDeband,
        setExportVideoDeband,
        exportVideoHisteq,
        setExportVideoHisteq,
        exportVideoLut3d,
        setExportVideoLut3d,
        exportVideoSharpen,
        setExportVideoSharpen,
        exportVideoEqPreset,
        setExportVideoEqPreset,
        exportVideoHue,
        setExportVideoHue,
        exportVideoGrain,
        setExportVideoGrain,
        exportVideoVignette,
        setExportVideoVignette,
        exportVideoBlur,
        setExportVideoBlur,
        exportAudioNormalize,
        setExportAudioNormalize,
        exportUserPresets,
        selectedUserPresetId,
        setSelectedUserPresetId,
        selectedExportUserPreset,
        lastExportPath,
        lastSnapshotPath,
        snapshotFormat,
        setSnapshotFormat,
        ffmpegExportSelectOptions,
        exportExtraArgsParsed,
        hydrateExportFieldsFromSettings,
        bumpManualExportEdit,
        handleSaveExportUserPreset,
        handleDeleteExportUserPreset,
        handleRenameExportUserPreset,
        handleOverwriteExportUserPreset,
        exportPreview,
        exportPreviewCommand,
        exportPreviewHint,
        handleCopyExportPreview,
        handleOpenLastExport,
        handleCopyLastExportPath,
        handleOpenLastSnapshot,
        handleCopyLastSnapshotPath,
        processingHistory,
        setProcessingHistory,
        processingHistoryBusy,
        processingHistoryFilter,
        processingHistoryWeeklySummary,
        setProcessingHistoryWeeklySummary,
        applyProcessingHistoryFilter,
        refreshProcessingHistory,
        exportVisibleProcessingHistory,
        reportBatchPathsAdded,
        hwEncoderProbe
      },
      terminal: {
        terminalBusy,
        terminalLine,
        setTerminalLine,
        terminalCommandInputId,
        terminalInlineSuggestions,
        terminalSuggestFocus,
        setTerminalSuggestFocus,
        terminalSuggestActiveIndex,
        setTerminalSuggestIndex,
        terminalSuggestBlurTimeoutRef,
        currentSourcePath,
        runTerminalLine,
        applyTerminalSuggest,
        appendTerminalToken,
        terminalHistory,
        copyTerminalOutputLine,
        terminalHintsSearchFieldId,
        terminalHintFilter,
        setTerminalHintFilter,
        visibleTerminalHints
      },
      downloads: {
        main: {
          downloadsOptionsBusy,
          downloadsHistoryBusy,
          downloadsUrl,
          setDownloadsUrl,
          downloadsMainUrlFieldId,
          downloadsNarrowLayout,
          downloadsStats,
          downloadsStatusFilter,
          setDownloadsStatusFilter,
          downloadsStatusFilterChips,
          downloadsRows,
          visibleDownloadsRows,
          setStatusHint,
          downloadsEmbeddedHistoryOpen,
          persistDownloadsEmbeddedHistoryOpen,
          visibleDownloadsHistory,
          downloadsHistoryCount: downloadsHistory.length,
          downloadsHistoryOutcomeFilter,
          setDownloadsHistoryOutcomeFilter,
          downloadsHistoryWeeklySummary: downloadsHistoryWeeklySummary ?? {
            since: 0,
            until: 0,
            total: 0,
            success: 0,
            error: 0,
            cancelled: 0
          },
          refreshDownloadsHistory,
          setDownloadsHistory,
          exportVisibleDownloadsHistory,
          downloadsEmbeddedLogOpen,
          persistDownloadsEmbeddedLogOpen,
          downloadsLogTargetRowId,
          downloadsLogLines,
          setDownloadsLogLines,
          setDownloadsLogTargetRowId
        },
        settings: {
          downloadsOptionsBusy,
          downloadsHistoryBusy,
          downloadsOptions,
          setDownloadsOptions,
          downloadsRailPanels,
          onRailSectionToggle: handleDownloadsRailSectionToggle,
          applyDownloadsOptionsPatch,
          downloadsOutputDirectory,
          setDownloadsOutputDirectory,
          refreshDownloadsOutputDirectory,
          setStatusHint,
          downloadsExpertHintFilter,
          setDownloadsExpertHintFilter,
          ytdlpCommandHintsFilteredByCategory,
          appendDownloadsExtraArgsToken,
          refreshDownloadsOptions
        },
        setWorkspaceTab,
        handleAddDownloadsFromMain,
        handleBatchAddDownloadsDone
      }
    },
    layout: {
      chromeBusy: {
        engineDownloadBusy,
        engineSummary,
        probePending,
        exportBusy,
        snapshotBusy,
        exportCancelBusy,
        terminalBusy,
        batchExportBusy,
        exportPresetSaving,
        enginePathsSaving,
        downloadsOptionsBusy,
        downloadsHistoryBusy
      },
      topbar: {
        workspaceTab,
        setWorkspaceTab,
        engineDownloadBusy,
        engineSummary,
        previewPath: preview?.path,
        exportBusy,
        exportCancelBusy,
        enginesOfferDownload,
        theme,
        setKnowledgeInitialSlug,
        setKnowledgeOpen,
        setAboutInfo,
        setAboutOpen,
        setEnginePathsOpen,
        handleOpenVideoFolderToolbar,
        handleOpenToolbar,
        handleCancelExport,
        handleEnginesDownload,
        handleUiLocaleToggle,
        toggleTheme
      },
      statusbar: {
        workspaceTab,
        engineDownloadBusy,
        engineSummary,
        engineVersionsLine,
        exportCodecStatusbarLabel,
        exportBusy,
        snapshotBusy,
        exportCancelBusy,
        probePending,
        batchExportBusy,
        statusHint
      },
      overlay: {
        aboutOpen,
        aboutInfo,
        setAboutOpen,
        knowledgeOpen,
        knowledgeInitialSlug,
        setKnowledgeOpen,
        setKnowledgeInitialSlug,
        uiLocaleRenderTick,
        onStatusHint: setStatusHint
      },
      exportPreset: {
        dialog: exportPresetNameDialog,
        exportPresetSaving,
        setDialog: setExportPresetNameDialog,
        handleSubmitExportPresetName
      },
      enginePaths: {
        enginePathsSaving,
        engineDownloadBusy,
        enginePathsDraft,
        setEnginePathsDraft,
        setEnginePathsOpen,
        handlePickEngine,
        handleClearDownloadedEngines,
        handleSaveEnginePaths
      }
    }
  }
}
