import type { DownloadsWindowUiStrings } from './downloads-window-ui-locale-types'

export const downloadsWindowUiStringsRu: DownloadsWindowUiStrings = {
  htmlLang: 'ru',
  pageTitle: 'FluxAlloy — менеджер загрузок',
  windowTitle: 'FluxAlloy — загрузки',
  workspaceTabsAria: 'Рабочие вкладки',
  editorTabDisabledTitle: 'Редактор находится в главном окне',
  editorTabLabel: 'Редактор',
  downloadsTabLabel: 'Загрузки',
  queueSectionAria: 'Очередь загрузок',
  urlsLabel: 'Введите URL (каждый с новой строки)',
  urlsHint:
    'Ссылки по строкам или перетаскивание текста/URL. Очередь последовательная §6. Если окно узкое (примерно до 960px), панель настроек yt-dlp переносится под очередь — в тулбаре есть «К настройкам».',
  addToQueue: 'Добавить в очередь',
  startAllTitle: 'Скачать все строки со статусом «Ожидание»',
  startAll: 'Начать загрузку',
  pauseToolbarTitleDefault: 'Приостановить загрузку (POSIX); на Windows недоступно',
  pauseLabel: 'Пауза',
  cancelTitle: 'Отменить текущую загрузку yt-dlp',
  cancel: 'Отмена',
  clearQueue: 'Очистить очередь',
  clearFinished: 'Убрать завершённые',
  statusFilterLabel: 'Статус',
  optQueueAll: 'Все',
  optQueueWaiting: 'Ожидание',
  optQueueRunning: 'В работе',
  optQueueDone: 'Готово',
  optQueueError: 'Ошибки',
  optQueueCancelled: 'Отмена',
  queueFilterHint:
    'Фильтр только для отображения таблицы; порядок очереди в основном процессе (main) не меняется.',
  queueToolbarHint:
    'Управление активной yt-dlp-задачей и содержимым очереди §6; пауза возможна только на платформах без ограничения yt-dlp.',
  queueSummaryInitial: 'Всего: 0',
  scrollToSettingsTitle: 'Прокрутить к панели настроек yt-dlp',
  scrollToSettings: 'К настройкам',
  queueTableCaption: 'Очередь загрузок yt-dlp',
  thNum: '#',
  thTitle: 'Название',
  thFmt: 'Формат',
  thSize: 'Размер',
  thProg: 'Прогресс',
  thSpd: 'Скорость',
  thEta: 'Осталось',
  thStatus: 'Статус',
  thActions: 'Действия',
  historySummary: 'История загрузок',
  historySectionHint:
    'Завершённые загрузки из userData §6; обновление и очистка трогают файл истории, фильтр «Исход» — только отображение таблицы.',
  refreshHistory: 'Обновить',
  clearHistory: 'Очистить историю',
  historyOutcomeLabel: 'Исход',
  histOptAll: 'Все',
  histOptSuccess: 'Успех',
  histOptError: 'Ошибка',
  histOptCancelled: 'Отмена',
  historyFilterHint: 'Фильтр только для отображения таблицы истории.',
  historyTableCaption: 'История завершённых загрузок',
  histThFinished: 'Завершено',
  histThName: 'Имя',
  histThUrl: 'Ссылка',
  histThOutcome: 'Исход',
  histThCode: 'Код',
  histThStatus: 'Статус',
  logSummary: 'Журнал операций',
  logSectionHint:
    'Потоковый вывод yt-dlp (stdout и stderr); «Очистить вид» убирает только текст в окне, «Сохранить журнал» — запись в файл по выбору.',
  saveLog: 'Сохранить журнал…',
  clearLogViewTitle: 'Очистить только текст на экране (файл не трогаем)',
  clearLogView: 'Очистить вид',
  logPreAriaLabel: 'Вывод yt-dlp: stdout и stderr',
  railAria: 'Настройки загрузки',
  railTitle: 'Настройки загрузки',
  railSubtitle:
    'Секции совпадают со встроенной вкладкой «Загрузки»: формат, метаданные, сохранение, сеть.',
  formatSummary: 'Формат',
  formatSectionHint:
    'Пресеты -f/-x, субтитры и сохранённые опции yt-dlp (userData/settings.json); шаблон -o ниже должен содержать %(ext)s.',
  formatQualityLabel: 'Формат / качество (-f)',
  playlistAudioGroupAria: 'Плейлист и аудио',
  wholePlaylistLabel: 'Весь плейлист',
  wholePlaylistAria: 'Весь плейлист',
  audioOnlyLabel: 'Только аудио',
  audioOnlyAria: 'Только аудио',
  subtitlesLabel: 'Субтитры §6.2',
  subOptNone: 'Не скачивать',
  subOptManual: 'Ручные дорожки (--write-subs)',
  subOptManualAuto: 'Ручные + автосгенерированные (--write-auto-subs)',
  subLangsLabel: 'Языки субтитров',
  subLangsPlaceholder: 'ru,en или all',
  metadataSummary: 'Метаданные',
  metadataSectionHint:
    'Cookies из браузера или файла Netscape, маскировка User-Agent §6; автозапуск в обработчик §6.4 и опционально ffmpeg-экспорт §7.2 в соседний файл.',
  cookiesLabel: 'Cookies §6.2',
  cookiesNone: 'Не использовать',
  cookiesChrome: 'Из браузера: Chrome',
  cookiesEdge: 'Из браузера: Edge',
  cookiesFirefox: 'Из браузера: Firefox',
  cookiesProfileLabel: 'Профиль / контейнер',
  cookiesProfilePlaceholder: 'имя профиля в Chrome, напр. Default или Profile 1',
  cookiesFileLabel: 'Файл cookies:',
  pickEllipsis: 'Выбрать…',
  clearCookiesTitle: 'Убрать файл из настроек',
  clearCookies: 'Очистить',
  impersonateLabel: 'Подмена клиента',
  impersonateOff: 'Выключено',
  openInHandlerPillLabel: 'Открывать результат в обработчике',
  openInHandlerAria: 'Открывать результат в обработчике после успеха',
  autoExportPillLabel: 'Затем авто-экспорт',
  autoExportAria: 'После авто-открытия запустить экспорт в файл рядом с загрузкой',
  enqueueBatchPillLabel: 'В пакет после загрузки',
  enqueueBatchAria: 'После успеха добавить видео в пакетный экспорт',
  autoStartBatchPillLabel: 'Авто-запуск пакета',
  autoStartBatchAria: 'Запустить пакетный экспорт после добавления в очередь',
  savingSummary: 'Сохранение',
  savingSectionHint:
    'Целевой каталог yt-dlp, шаблон имени (-o); кнопка «Сохранить параметры» записывает настройки в userData/settings.json §6.',
  outDirLabel: 'Каталог загрузок:',
  openOutTitle: 'Открыть текущий каталог загрузок в проводнике',
  openOut: 'Открыть',
  pickOut: 'Выбрать…',
  resetOutTitle: 'Использовать каталог по умолчанию в userData',
  resetOut: 'По умолчанию',
  tmplLabel: 'Шаблон имени (-o)',
  applyOpts: 'Сохранить параметры',
  tmplReset: 'Шаблон по умолчанию',
  networkSummary: 'Сеть',
  networkSectionHint:
    'Ограничение скорости скачивания, параметры yt-dlp и профиль автоповтора строки очереди при ошибке §6.4.',
  rateLimitLabel: 'Ограничение скорости (--limit-rate)',
  rateLimitPlaceholder: '500K или 2M',
  retriesLabel: 'Повторы при ошибках (--retries)',
  retriesPlaceholder: '0–99',
  fragmentRetriesLabel: 'Повторы фрагментов (--fragment-retries)',
  queueRetryLabel: 'Повтор строки при сбое',
  queueRetryOff: 'Выключено',
  queueRetryLight: 'Лёгкий (1 повтор, 2.5 с)',
  queueRetryNormal: 'Обычный (2 повтора: 3 с + 8 с)',
  queueRetryPersistent: 'Устойчивый (3 повтора: 5 с + 15 с + 45 с)',
  expertSummary: 'Эксперт и превью',
  expertSectionHintBeforeLinks:
    'Белый список аргументов §6.3: правки здесь добавляются к финальной командной строке yt-dlp; ниже живое превью аргументов (argv). То же поле — во вкладке «Загрузки» главного окна. Онлайн:',
  expertSectionHintAfterLinks: '.',
  docFormats: 'форматы',
  docOutputTemplate: 'шаблон вывода',
  docPostprocess: 'постобработка',
  extraArgsLabel: 'Дополнительные аргументы (без оболочки)',
  extraArgsPlaceholder: 'Например: --write-sub --sub-lang ru',
  previewOutDirLabel: 'Другой каталог для превью пути шаблона -o',
  previewOutDirPlaceholder: 'Только путь в строке для превью аргументов (argv)',
  argsPreviewLabel: 'Превью аргументов (argv)',
  argsPreviewAria: 'Превью аргументов командной строки yt-dlp (argv)',
  hintsPanelSummary: 'Справочник флагов',
  hintCatalogIntro:
    'Краткий справочник: введите часть флага или описания, нажмите на токен в списке — он добавится в «Дополнительные аргументы». Под каждым пунктом — пояснение простыми словами.',
  hintCatalogFilterLabel: 'Поиск по справочнику аргументов (argv)',
  hintFilterPlaceholder: 'Например: --cookies или --sub',
  hintFilterAria: 'Поиск по токенам и описаниям справочника аргументов (argv)',
  hintListAria: 'Справочник флагов с описаниями',
  footerNote:
    'Отдельный preload IPC только для этого окна. yt-dlp запускается из main через spawn без оболочки.',
  topbarCluster: {
    toolbarAria: 'Действия',
    inspector: 'Инспектор ffprobe §9',
    focusUrl: 'К полю URL (лента ввода §6)',
    mainEditor: 'Главное окно (редактор)',
    enginePaths: 'Пути к движкам ffmpeg / yt-dlp / ffprobe',
    about: 'О программе'
  },
  pillOn: 'Вкл',
  pillOff: 'Выкл',
  hintCategoryFallback: 'Прочее',
  outcomeSuccess: 'Успех',
  outcomeCancelled: 'Отмена',
  outcomeError: 'Ошибка',
  historyEmpty: 'Записей пока нет',
  historyNoMatchingFilter: 'Нет записей с таким исходом',
  confirmClearHistory: 'Удалить все записи истории загрузок?',
  hintsCatalogUnavailable: 'Справочник недоступен.',
  hintsCatalogUnavailableShort: 'Справочник недоступен',
  hintsNoMatches: 'Нет совпадений.',
  queueTotal: 'Всего:',
  queueWaiting: 'ждёт:',
  queueRunning: 'в работе:',
  queueDone: 'готово:',
  queueErrors: 'ошибок:',
  queueCancelled: 'отменено:',
  queueEmpty: 'Очередь пуста',
  queueNoMatchingFilter: 'Нет строк с таким статусом',
  rowCancelYtdlp: 'Отменить текущую загрузку yt-dlp (эта строка)',
  rowResumeYtdlp: 'Продолжить загрузку (SIGCONT)',
  rowPauseYtdlp: 'Приостановить загрузку (SIGSTOP)',
  rowStartThisLine: 'Скачать только эту строку',
  rowRetryDownload: 'Сбросить статус и скачать эту строку заново',
  rowOpenInFlux: 'Открыть скачанный файл в FluxAlloy',
  rowOpenFile: 'Открыть скачанный файл',
  rowShowInFolder: 'Показать файл в папке',
  rowOpenDownloadFolder: 'Открыть папку загрузок yt-dlp (куда сохраняется файл)',
  rowMoveUp: 'Переместить строку вверх в очереди',
  rowMoveDown: 'Переместить строку вниз в очереди',
  rowRemoveFromQueue: 'Удалить строку из очереди',
  histReenqueueUrl: 'Добавить этот URL в очередь повторно',
  histOpenInFlux: 'Открыть скачанный файл в FluxAlloy',
  histOpenFile: 'Открыть скачанный файл',
  histShowInFolder: 'Показать файл в папке',
  pauseUnsupportedWinTitle: 'Пауза процесса yt-dlp недоступна в Windows (нужны SIGSTOP/SIGCONT).',
  pauseTitleSigstop: 'Приостановить текущую загрузку yt-dlp (SIGSTOP)',
  resumeTitleSigcont: 'Возобновить загрузку yt-dlp (SIGCONT)',
  pauseToolbarResume: 'Продолжить',
  logEmptyAlert: 'Журнал пуст — пока нечего сохранять.',
  logLinesWord: 'стр.'
}
