import type { DownloadsWindowUiStrings } from './downloads-window-ui-locale-types'

export const downloadsWindowUiStringsEn: DownloadsWindowUiStrings = {
  htmlLang: 'en',
  pageTitle: 'FluxAlloy — download manager',
  windowTitle: 'FluxAlloy — downloads',
  workspaceTabsAria: 'Workspace tabs',
  editorTabDisabledTitle: 'The editor lives in the main window',
  editorTabLabel: 'Editor',
  downloadsTabLabel: 'Downloads',
  queueSectionAria: 'Download queue',
  urlsLabel: 'Enter URLs (one per line)',
  urlsHint:
    'One URL per line or drop text/URLs. The queue runs sequentially. If the window is narrow (about up to 960px), yt-dlp settings move below the queue — use “To settings” in the toolbar.',
  addToQueue: 'Add to queue',
  startAllTitle: 'Download all rows waiting in the queue',
  startAll: 'Start download',
  pauseToolbarTitleDefault: 'Pause download (POSIX); not available on Windows',
  pauseLabel: 'Pause',
  cancelTitle: 'Cancel the current yt-dlp download',
  cancel: 'Cancel',
  clearQueue: 'Clear queue',
  clearFinished: 'Remove finished',
  statusFilterLabel: 'Status',
  optQueueAll: 'All',
  optQueueWaiting: 'Waiting',
  optQueueRunning: 'Running',
  optQueueDone: 'Done',
  optQueueError: 'Errors',
  optQueueCancelled: 'Cancelled',
  queueFilterHint: 'Display-only filter; queue order in main is unchanged.',
  queueToolbarHint:
    'Controls the active yt-dlp job and queue contents; pause works only where SIGSTOP/SIGCONT are supported.',
  queueSummaryInitial: 'Total: 0',
  scrollToSettingsTitle: 'Scroll to yt-dlp settings',
  scrollToSettings: 'To settings',
  queueTableCaption: 'yt-dlp download queue',
  thNum: '#',
  thTitle: 'Title',
  thFmt: 'Format',
  thSize: 'Size',
  thProg: 'Progress',
  thSpd: 'Speed',
  thEta: 'ETA',
  thStatus: 'Status',
  thActions: 'Actions',
  historySummary: 'Download history',
  historySectionHint:
    'Finished downloads from userData; refresh/clear touch the history file. The outcome filter is display-only.',
  refreshHistory: 'Refresh',
  clearHistory: 'Clear history',
  historyOutcomeLabel: 'Outcome',
  histOptAll: 'All',
  histOptSuccess: 'Success',
  histOptError: 'Error',
  histOptCancelled: 'Cancelled',
  historyFilterHint: 'Display-only filter for the history table.',
  historyTableCaption: 'Finished download history',
  histThFinished: 'Finished',
  histThName: 'Name',
  histThUrl: 'URL',
  histThOutcome: 'Outcome',
  histThCode: 'Code',
  histThStatus: 'Status',
  logSummary: 'Operation log',
  logSectionHint:
    'Streaming stdout/stderr from yt-dlp. “Clear view” only clears on-screen text; “Save log…” writes to a file you pick.',
  saveLog: 'Save log…',
  clearLogViewTitle: 'Clear on-screen text only (does not delete files)',
  clearLogView: 'Clear view',
  logPreAriaLabel: 'yt-dlp stdout and stderr',
  railAria: 'Download settings',
  railTitle: 'Download settings',
  railSubtitle: 'Sections mirror the in-app tab: format, metadata, saving, network.',
  formatSummary: 'Format',
  formatSectionHint:
    'Presets for -f/-x, subtitles, and saved yt-dlp options (userData/settings.json). The -o template below must include %(ext)s.',
  formatQualityLabel: 'Format / quality (-f)',
  playlistAudioGroupAria: 'Playlist and audio',
  wholePlaylistLabel: 'Full playlist',
  wholePlaylistAria: 'Full playlist',
  audioOnlyLabel: 'Audio only',
  audioOnlyAria: 'Audio only',
  subtitlesLabel: 'Subtitles',
  subOptNone: 'Do not download',
  subOptManual: 'Manual tracks (--write-subs)',
  subOptManualAuto: 'Manual + auto-generated (--write-auto-subs)',
  subLangsLabel: 'Subtitle languages',
  subLangsPlaceholder: 'ru,en or all',
  metadataSummary: 'Metadata',
  metadataSectionHint:
    'Browser or Netscape cookies file, client impersonation; optional open-in-handler after success and ffmpeg export beside the download.',
  cookiesLabel: 'Cookies',
  cookiesNone: 'Do not use',
  cookiesChrome: 'From browser: Chrome',
  cookiesEdge: 'From browser: Edge',
  cookiesFirefox: 'From browser: Firefox',
  cookiesProfileLabel: 'Profile / container',
  cookiesProfilePlaceholder: 'e.g. Default or Profile 1',
  cookiesFileLabel: 'Cookies file:',
  pickEllipsis: 'Choose…',
  clearCookiesTitle: 'Remove file from settings',
  clearCookies: 'Clear',
  impersonateLabel: 'Client impersonation',
  impersonateOff: 'Off',
  openInHandlerPillLabel: 'Open result in handler',
  openInHandlerAria: 'Open downloaded file in handler after success',
  autoExportPillLabel: 'Then auto-export',
  autoExportAria: 'After auto-open, run export to a file next to the download',
  enqueueBatchPillLabel: 'Enqueue to batch',
  enqueueBatchAria: 'After success, add video to batch export queue',
  autoStartBatchPillLabel: 'Auto-start batch',
  autoStartBatchAria: 'Start batch export after enqueue',
  savingSummary: 'Saving',
  savingSectionHint:
    'yt-dlp output directory and filename template (-o). “Save settings” writes to userData/settings.json.',
  outDirLabel: 'Download folder:',
  openOutTitle: 'Open the current download folder in the file manager',
  openOut: 'Open',
  pickOut: 'Choose…',
  resetOutTitle: 'Use the default folder under userData',
  resetOut: 'Default',
  tmplLabel: 'Filename template (-o)',
  applyOpts: 'Save settings',
  tmplReset: 'Reset template',
  networkSummary: 'Network',
  networkSectionHint:
    'Rate limit, yt-dlp retry options, and automatic row retry profile after failures.',
  rateLimitLabel: 'Rate limit (--limit-rate)',
  rateLimitPlaceholder: '500K or 2M',
  retriesLabel: 'Retries on errors (--retries)',
  retriesPlaceholder: '0–99',
  fragmentRetriesLabel: 'Fragment retries (--fragment-retries)',
  queueRetryLabel: 'Row retry on failure',
  queueRetryOff: 'Off',
  queueRetryLight: 'Light (1 retry, 2.5 s)',
  queueRetryNormal: 'Normal (2 retries: 3 s + 8 s)',
  queueRetryPersistent: 'Persistent (3 retries: 5 s + 15 s + 45 s)',
  expertSummary: 'Expert argv',
  expertSectionHintBeforeLinks:
    'Allow-listed arguments: edits here are appended to the final yt-dlp argv; live preview below. Same argv field as the Downloads tab in the main window. Online:',
  expertSectionHintAfterLinks: '.',
  docFormats: 'formats',
  docOutputTemplate: 'output template',
  docPostprocess: 'post-processing',
  extraArgsLabel: 'Extra arguments (no shell)',
  extraArgsPlaceholder: 'e.g. --write-sub --sub-lang ru',
  previewOutDirLabel: 'Different folder for -o preview',
  previewOutDirPlaceholder: 'Preview argv path string only',
  argsPreviewLabel: 'Argv preview',
  argsPreviewAria: 'yt-dlp argv preview',
  hintsPanelSummary: 'Flag reference',
  hintCatalogIntro:
    'Short catalog: type part of a flag or description, then click a token in the list — it is appended to “Extra arguments”. Each row has a plain-language note.',
  hintCatalogFilterLabel: 'Search the argv catalog',
  hintFilterPlaceholder: 'e.g. --cookies or --sub',
  hintFilterAria: 'Search the argv reference by token or description',
  hintListAria: 'Flag reference with descriptions',
  footerNote:
    'Dedicated preload IPC for this window only. yt-dlp is spawned from main without a shell.',
  topbarCluster: {
    toolbarAria: 'Actions',
    inspector: 'ffprobe inspector',
    focusUrl: 'Focus URL field (input strip)',
    mainEditor: 'Main editor window',
    enginePaths: 'Paths to ffmpeg / yt-dlp / ffprobe',
    about: 'About'
  },
  pillOn: 'On',
  pillOff: 'Off',
  hintCategoryFallback: 'Other',
  outcomeSuccess: 'Success',
  outcomeCancelled: 'Cancelled',
  outcomeError: 'Error',
  historyEmpty: 'No entries yet',
  historyNoMatchingFilter: 'No entries for this outcome',
  confirmClearHistory: 'Delete all download history entries?',
  hintsCatalogUnavailable: 'Reference unavailable.',
  hintsCatalogUnavailableShort: 'Reference unavailable',
  hintsNoMatches: 'No matches.',
  queueTotal: 'Total:',
  queueWaiting: 'waiting:',
  queueRunning: 'running:',
  queueDone: 'done:',
  queueErrors: 'errors:',
  queueCancelled: 'cancelled:',
  queueEmpty: 'Queue is empty',
  queueNoMatchingFilter: 'No rows for this status',
  rowCancelYtdlp: 'Cancel current yt-dlp download (this row)',
  rowResumeYtdlp: 'Resume download (SIGCONT)',
  rowPauseYtdlp: 'Pause download (SIGSTOP)',
  rowStartThisLine: 'Download this row only',
  rowRetryDownload: 'Reset status and download this row again',
  rowOpenInFlux: 'Open downloaded file in FluxAlloy',
  rowOpenFile: 'Open downloaded file',
  rowShowInFolder: 'Show file in folder',
  rowOpenDownloadFolder: 'Open yt-dlp download folder (where the file is saved)',
  rowMoveUp: 'Move row up in queue',
  rowMoveDown: 'Move row down in queue',
  rowRemoveFromQueue: 'Remove row from queue',
  histReenqueueUrl: 'Enqueue this URL again',
  histOpenInFlux: 'Open downloaded file in FluxAlloy',
  histOpenFile: 'Open downloaded file',
  histShowInFolder: 'Show file in folder',
  pauseUnsupportedWinTitle:
    'Pausing yt-dlp is not available on Windows (SIGSTOP/SIGCONT required).',
  pauseTitleSigstop: 'Pause current yt-dlp download (SIGSTOP)',
  resumeTitleSigcont: 'Resume yt-dlp download (SIGCONT)',
  pauseToolbarResume: 'Resume',
  logEmptyAlert: 'Log is empty — nothing to save yet.',
  logLinesWord: 'lines'
}
