/**
 * §9 — поля `format.*` (не tags): parse + export из locale-шаблонов.
 * Скалярные `format.tags.*` — `ffprobe-format-tag-registry.ts`.
 */
export type { FfprobeFormatJsonSlice } from './ffprobe-container-field-registry-parse'
export {
  parseFfprobeContainerFieldsFromFormat,
  parseFfprobeFormatBitRateKbps,
  parseFfprobeFormatCompatibleBrands,
  parseFfprobeFormatCreationTime,
  parseFfprobeFormatDurationSec,
  parseFfprobeFormatDurationTs,
  parseFfprobeFormatFilename,
  parseFfprobeFormatFlags,
  parseFfprobeFormatMajorBrand,
  parseFfprobeFormatNbPrograms,
  parseFfprobeFormatNbChapters,
  parseFfprobeFormatNbStreams,
  parseFfprobeFormatProbeScore,
  parseFfprobeFormatProbeSize,
  parseFfprobeFormatSize,
  parseFfprobeFormatStartTimeSec,
  parseFfprobeFormatTimeBase
} from './ffprobe-container-field-registry-parse'
export {
  collectFfprobeContainerScalarExportLines,
  ffprobeContainerFilenameBasename,
  formatFfprobeContainerBitRateCompact,
  formatFfprobeContainerBitRateExportLine,
  formatFfprobeContainerBrandExportLine,
  formatFfprobeContainerCreationTimeExportLine,
  formatFfprobeContainerDiagnosticsCompactLine,
  formatFfprobeContainerDiagnosticsExportLine,
  formatFfprobeContainerDurationSecCompact,
  formatFfprobeContainerDurationSecExportLine,
  formatFfprobeContainerDurationTsCompact,
  formatFfprobeContainerDurationTsExportLine,
  formatFfprobeContainerFilenameCompact,
  formatFfprobeContainerFilenameExportLine,
  formatFfprobeContainerFormatFlagsCompact,
  formatFfprobeContainerOffsetTimingCompactLine,
  formatFfprobeContainerOffsetTimingExportLine,
  formatFfprobeContainerProbeLayoutCompactLine,
  formatFfprobeContainerProbeLayoutExportLine,
  formatFfprobeContainerProbeSizeCompact,
  formatFfprobeContainerProbeSizeExportLine,
  formatFfprobeContainerSizeCompact,
  formatFfprobeContainerSizeExportLine,
  formatFfprobeContainerStartOffsetCompactLine,
  formatFfprobeContainerStartOffsetExportLine,
  formatFfprobeContainerStartTimeCompact,
  formatFfprobeContainerStartTimeExportLine,
  formatFfprobeContainerStartTimeRealExportLine,
  formatFfprobeContainerTimeBaseExportLine,
  formatFfprobeContainerTimingProbeCompactLine,
  formatFfprobeContainerTimingProbeExportLine,
  formatFfprobeFormatFlagsExportLine,
  formatFfprobeNbProgramsExportLine,
  formatFfprobeNbChaptersExportLine,
  formatFfprobeNbStreamsExportLine,
  formatFfprobeProbeScoreExportLine
} from './ffprobe-container-field-registry-format'
