/**
 * Единый реестр строк IPC между main и preload/renderer.
 * Имена каналов не дублируем литералами — импортируем отсюда, чтобы main и preload не расходились.
 */

/** Главное окно: invoke/handle + подписки на события из main. */
export const mainWindowIpc = {
  settingsGet: 'velorix:settings-get',
  settingsSetUiLocale: 'velorix:settings-set-ui-locale',
  settingsSetTheme: 'velorix:settings-set-theme',
  settingsSetFfmpegExportEncodePreset: 'velorix:settings-set-ffmpeg-export-encode-preset',
  settingsSetFfmpegExportVideoCodec: 'velorix:settings-set-ffmpeg-export-video-codec',
  settingsSetFfmpegExportContainer: 'velorix:settings-set-ffmpeg-export-container',
  settingsSetFfmpegExportCrf: 'velorix:settings-set-ffmpeg-export-crf',
  settingsSetFfmpegExportAudioBitrate: 'velorix:settings-set-ffmpeg-export-audio-bitrate',
  settingsSetFfmpegExportAudioMode: 'velorix:settings-set-ffmpeg-export-audio-mode',
  settingsSetFfmpegExportVideoBitrate: 'velorix:settings-set-ffmpeg-export-video-bitrate',
  settingsSetFfmpegExportTwoPass: 'velorix:settings-set-ffmpeg-export-two-pass',
  settingsSetFfmpegExportEconomyMode: 'velorix:settings-set-ffmpeg-export-economy-mode',
  settingsSetFfmpegExportBenchmarkLoadThreshold:
    'velorix:settings-set-ffmpeg-export-benchmark-load-threshold',
  settingsSetFfmpegExportHwDecode: 'velorix:settings-set-ffmpeg-export-hw-decode',
  settingsSetFfmpegExportExtraArgsLine: 'velorix:settings-set-ffmpeg-export-extra-args-line',
  settingsSetFfmpegExportBatchOutputSuffix:
    'velorix:settings-set-ffmpeg-export-batch-output-suffix',
  settingsSetFfmpegExportBatchOutputDirectory:
    'velorix:settings-set-ffmpeg-export-batch-output-dir',
  settingsSetEditorUrlPasteBehavior: 'velorix:settings-set-editor-url-paste-behavior',
  settingsSetConfirmCloseOnQuit: 'velorix:settings-set-confirm-close-on-quit',
  settingsSetFfmpegExportFps: 'velorix:settings-set-ffmpeg-export-fps',
  settingsSetFfmpegExportScalePreset: 'velorix:settings-set-ffmpeg-export-scale-preset',
  settingsSetFfmpegExportVideoTransform: 'velorix:settings-set-ffmpeg-export-video-transform',
  settingsSetFfmpegExportCropPreset: 'velorix:settings-set-ffmpeg-export-crop-preset',
  settingsSetFfmpegExportAudioGainDb: 'velorix:settings-set-ffmpeg-export-audio-gain-db',
  settingsSetFfmpegExportStripMetadata: 'velorix:settings-set-ffmpeg-export-strip-metadata',
  settingsSetFfmpegExportStripChapters: 'velorix:settings-set-ffmpeg-export-strip-chapters',
  settingsSetFfmpegExportSubtitleMode: 'velorix:settings-set-ffmpeg-export-subtitle-mode',
  settingsSetFfmpegExportVideoDenoise: 'velorix:settings-set-ffmpeg-export-video-denoise',
  settingsSetFfmpegExportVideoDeband: 'velorix:settings-set-ffmpeg-export-video-deband',
  settingsSetFfmpegExportVideoHisteq: 'velorix:settings-set-ffmpeg-export-video-histeq',
  settingsSetFfmpegExportVideoLut3d: 'velorix:settings-set-ffmpeg-export-video-lut3d',
  settingsSetFfmpegExportVideoSharpen: 'velorix:settings-set-ffmpeg-export-video-sharpen',
  settingsSetFfmpegExportVideoEqPreset: 'velorix:settings-set-ffmpeg-export-video-eq-preset',
  settingsSetFfmpegExportVideoGrain: 'velorix:settings-set-ffmpeg-export-video-grain',
  settingsSetFfmpegExportVideoVignette: 'velorix:settings-set-ffmpeg-export-video-vignette',
  settingsSetFfmpegExportVideoBlur: 'velorix:settings-set-ffmpeg-export-video-blur',
  settingsSetFfmpegExportVideoDeinterlace: 'velorix:settings-set-ffmpeg-export-video-deinterlace',
  settingsSetFfmpegExportVideoHue: 'velorix:settings-set-ffmpeg-export-video-hue',
  settingsSetFfmpegExportAudioNormalize: 'velorix:settings-set-ffmpeg-export-audio-normalize',
  settingsSetFfmpegExportUserPresets: 'velorix:settings-set-ffmpeg-export-user-presets',
  settingsApplyFfmpegExportSnapshot: 'velorix:settings-apply-ffmpeg-export-snapshot',
  settingsSetFfmpegSnapshotFormat: 'velorix:settings-set-ffmpeg-snapshot-format',
  settingsSetEnginePaths: 'velorix:settings-set-engine-paths',
  /** §4.1 — частичное обновление раскрытых секций главного окна (persist в settings.json). */
  settingsMergeMainWindowUiPanels: 'velorix:settings-merge-main-window-ui-panels',
  pickEngineExecutable: 'velorix:pick-engine-executable',
  enginesStatus: 'velorix:engines-status',
  enginesShouldOfferDownload: 'velorix:engines-should-offer-download',
  enginesDownload: 'velorix:engines-download',
  enginesCheckUpdatesAndDownload: 'velorix:engines-check-updates-and-download',
  enginesClearUserBin: 'velorix:engines-clear-user-bin',
  enginesProbeHwEncoders: 'velorix:engines-probe-hw-encoders',
  enginesProgress: 'velorix:engines-progress',
  openVideoDialog: 'velorix:open-video-dialog',
  openVideoFolderDialog: 'velorix:open-video-folder-dialog',
  previewGrantPath: 'velorix:preview-grant-path',
  persistLastSource: 'velorix:persist-last-source',
  restoreLastSource: 'velorix:restore-last-source',
  mediaProbe: 'velorix:media-probe',
  terminalHints: 'velorix:terminal-hints',
  terminalRun: 'velorix:terminal-run',
  knowledgeListArticles: 'velorix:knowledge-list-articles',
  knowledgeReadArticle: 'velorix:knowledge-read-article',
  clipboardReadText: 'velorix:clipboard-read-text',
  clipboardWriteText: 'velorix:clipboard-write-text',
  saveTextWithDialog: 'velorix:save-text-with-dialog',
  appAboutInfo: 'velorix:app-about-info',
  diagnosticsListFolders: 'velorix:diagnostics-list-folders',
  diagnosticsOpenFolder: 'velorix:diagnostics-open-folder',
  diagnosticsOpenMainLog: 'velorix:diagnostics-open-main-log',
  diagnosticsCreateSupportZip: 'velorix:diagnostics-create-support-zip',
  diagnosticsMaintenanceSnapshot: 'velorix:diagnostics-maintenance-snapshot',
  diagnosticsCleanMaintenance: 'velorix:diagnostics-clean-maintenance',
  processingHistoryGet: 'velorix:processing-history-get',
  processingHistoryWeeklySummary: 'velorix:processing-history-weekly-summary',
  processingHistoryClear: 'velorix:processing-history-clear',
  processingHistoryOpenOutput: 'velorix:processing-history-open-output',
  processingHistoryOpenInputInHandler: 'velorix:processing-history-open-input-in-handler',
  processingHistoryRepeatWorkflowScenario: 'velorix:processing-history-repeat-workflow-scenario',
  processingHistoryChanged: 'velorix:processing-history-changed',
  windowsExplorerContextMenuStatus: 'velorix:windows-explorer-context-menu-status',
  windowsExplorerContextMenuSetEnabled: 'velorix:windows-explorer-context-menu-set-enabled',
  windowsExplorerContextMenuRegisterNow: 'velorix:windows-explorer-context-menu-register-now',
  windowsExplorerContextMenuUnregister: 'velorix:windows-explorer-context-menu-unregister',
  windowsFileAssociationStatus: 'velorix:windows-file-association-status',
  windowsFileAssociationSetEnabled: 'velorix:windows-file-association-set-enabled',
  windowsFileAssociationRegisterNow: 'velorix:windows-file-association-register-now',
  windowsFileAssociationUnregister: 'velorix:windows-file-association-unregister',
  openWindowsDefaultAppsSettings: 'velorix:open-windows-default-apps-settings',
  openDownloadsWindow: 'velorix:open-downloads-window',
  /** §4.3 — компактное окно прогресса (`#mini-player`). */
  miniPlayerShow: 'velorix:mini-player-show',
  miniPlayerHide: 'velorix:mini-player-hide',
  miniPlayerGetSnapshot: 'velorix:mini-player-get-snapshot',
  miniPlayerSetAlwaysOnTop: 'velorix:mini-player-set-always-on-top',
  miniPlayerFocusMain: 'velorix:mini-player-focus-main',
  /** §9 — отдельное окно инспектора ffprobe (`#inspector`). */
  openInspectorWindow: 'velorix:open-inspector-window',
  inspectorBootstrap: 'velorix:inspector-bootstrap',
  /** Main → renderer окна инспектора: проанализировать указанный путь. */
  inspectorTargetMediaPath: 'velorix:inspector-target-media-path',
  exportStart: 'velorix:export-start',
  exportBenchmarkEncoders: 'velorix:export-benchmark-encoders',
  exportBenchmarkProgress: 'velorix:export-benchmark-progress',
  extractFrames: 'velorix:extract-frames',
  extractFramesProgress: 'velorix:extract-frames-progress',
  generateVideoSprite: 'velorix:generate-video-sprite',
  mediaUtilitiesRepairRemux: 'velorix:media-utilities-repair-remux',
  mediaUtilitiesCheckIntegrity: 'velorix:media-utilities-check-integrity',
  mediaUtilitiesGenerateNoise: 'velorix:media-utilities-generate-noise',
  mediaUtilitiesComputeFileHash: 'velorix:media-utilities-compute-file-hash',
  mediaUtilitiesConvertImage: 'velorix:media-utilities-convert-image',
  mediaUtilitiesPickSlideshowImages: 'velorix:media-utilities-pick-slideshow-images',
  mediaUtilitiesCreateImageSlideshow: 'velorix:media-utilities-create-image-slideshow',
  exportResolveBundledLutCubePath: 'velorix:export-resolve-bundled-lut-cube-path',
  exportCancel: 'velorix:export-cancel',
  exportOpenOutput: 'velorix:export-open-output',
  exportProgress: 'velorix:export-progress',
  batchExportGetSnapshot: 'velorix:batch-export-get-snapshot',
  batchExportPickFiles: 'velorix:batch-export-pick-files',
  batchExportPickFolder: 'velorix:batch-export-pick-folder',
  batchExportPickOutputFolder: 'velorix:batch-export-pick-output-folder',
  batchExportRevealSharedOutputFolder: 'velorix:batch-export-reveal-shared-output-folder',
  batchExportAddPaths: 'velorix:batch-export-add-paths',
  batchExportRemoveRows: 'velorix:batch-export-remove-rows',
  batchExportClear: 'velorix:batch-export-clear',
  batchExportMoveRow: 'velorix:batch-export-move-row',
  batchExportReorderRow: 'velorix:batch-export-reorder-row',
  batchExportSetConcurrency: 'velorix:batch-export-set-concurrency',
  batchExportStart: 'velorix:batch-export-start',
  batchExportCancel: 'velorix:batch-export-cancel',
  batchExportRetryFailed: 'velorix:batch-export-retry-failed',
  batchExportRetryRows: 'velorix:batch-export-retry-rows',
  batchExportClearCompleted: 'velorix:batch-export-clear-completed',
  batchExportAddFromDownloadsDone: 'velorix:batch-export-add-from-downloads-done',
  batchExportAddFromHistoryInputs: 'velorix:batch-export-add-from-history-inputs',
  batchExportRetryFailedAndStart: 'velorix:batch-export-retry-failed-and-start',
  batchExportListInputPaths: 'velorix:batch-export-list-input-paths',
  batchExportListOutputPaths: 'velorix:batch-export-list-output-paths',
  batchExportRemoveWaiting: 'velorix:batch-export-remove-waiting',
  batchExportOpenInput: 'velorix:batch-export-open-input',
  batchExportSnapshot: 'velorix:batch-export-snapshot',
  snapshotFrame: 'velorix:snapshot-frame',
  logRenderer: 'velorix:log-renderer',
  previewOpened: 'velorix:preview-opened',
  themeChanged: 'velorix:theme-changed',
  uiLocaleChanged: 'velorix:ui-locale-changed',
  openEnginePaths: 'velorix:open-engine-paths',
  /** Main → renderer: открыть единое окно настроек; payload — `AppSettingsDialogSection` или пусто. */
  openSettings: 'velorix:open-settings',
  enginePathsChanged: 'velorix:engine-paths-changed',
  settingsBackupExport: 'velorix:settings-backup-export',
  settingsBackupImport: 'velorix:settings-backup-import',
  settingsResetToDefaults: 'velorix:settings-reset-to-defaults',
  /** Main → renderer: полная замена settings.json после импорта из меню «Сервис». */
  settingsBackupImported: 'velorix:settings-backup-imported',
  /** §20 — экспорт пользовательских пресетов ffmpeg (JSON bundle). */
  presetsExportExport: 'velorix:presets-export-export',
  /** §20 — импорт пользовательских пресетов ffmpeg. */
  presetsExportImport: 'velorix:presets-export-import',
  /** §20 — клонировать встроенный пресет в пользовательский. */
  presetsExportCloneBuiltin: 'velorix:presets-export-clone-builtin',
  /** Main → renderer: изменился каталог `Presets/export` или список пресетов. */
  exportPresetsDiskChanged: 'velorix:export-presets-disk-changed',
  openAbout: 'velorix:open-about',
  openMediaFileUtilities: 'velorix:open-media-file-utilities',
  openExternalFilterScript: 'velorix:open-external-filter-script',
  externalFilterScriptPickFile: 'velorix:external-filter-script-pick-file',
  externalFilterScriptApply: 'velorix:external-filter-script-apply',
  /** §10/§11 — реестр сценариев и задач в userData/workflows. */
  workflowScenariosList: 'velorix:workflow-scenarios-list',
  workflowScenariosGet: 'velorix:workflow-scenarios-get',
  workflowScenariosSave: 'velorix:workflow-scenarios-save',
  workflowScenariosDelete: 'velorix:workflow-scenarios-delete',
  scheduledTasksList: 'velorix:scheduled-tasks-list',
  scheduledTasksSave: 'velorix:scheduled-tasks-save',
  scheduledTasksDelete: 'velorix:scheduled-tasks-delete',
  scheduledTasksSetEnabled: 'velorix:scheduled-tasks-set-enabled',
  workflowPickWatchFolder: 'velorix:workflow-pick-watch-folder',
  /** Renderer → main: поставить прогон сценария по уже открытому медиафайлу. */
  workflowRunScenarioOnFile: 'velorix:workflow-run-scenario-on-file',
  workflowRunScenarioOnUrl: 'velorix:workflow-run-scenario-on-url',
  workflowCapabilities: 'velorix:workflow-capabilities',
  /** Main → renderer: новый файл в папке задачи watch-folder. */
  workflowWatchFolderDetected: 'velorix:workflow-watch-folder-detected',
  workflowWatchFolderRunFinished: 'velorix:workflow-watch-folder-run-finished',
  /** Main → renderer: открыть планировщик / конструктор сценариев. */
  openWorkflowPlanner: 'velorix:open-workflow-planner',
  openWorkflowScenarioBuilder: 'velorix:open-workflow-scenario-builder',
  /** Main → все окна с главным preload: актуальный снимок `mainWindowUiPanels` после merge §4.1. */
  mainWindowUiPanelsChanged: 'velorix:main-window-ui-panels-changed',
  /** Main → главное окно: снимок `downloadsWindowUiPanels` после merge (вкладка «Загрузки» ↔ pop-out). */
  downloadsWindowUiPanelsChanged: 'velorix:downloads-window-ui-panels-changed',
  /** Main → вкладка «Загрузки» и pop-out: каталог вывода yt-dlp после pick/clear/merge settings. */
  downloadsOutputDirectoryChanged: 'velorix:downloads-output-directory-changed',
  /** Main → вкладка «Загрузки» и pop-out: yt-dlp CLI/options изменились (клиенты делают getCliOptions). */
  downloadsCliOptionsChanged: 'velorix:downloads-cli-options-changed'
} as const

/** Окно yt-dlp: invoke/handle + push (`queueSnapshot`, `log`). */
export const downloadsIpc = {
  queueSnapshot: 'velorix-downloads-state',
  log: 'velorix-downloads-log',
  getSnapshot: 'velorix-downloads-get-snapshot',
  addLines: 'velorix-downloads-add-lines',
  /** §6 — первый URL из текста: скачать одной строкой и открыть результат в главном редакторе. */
  downloadFirstUrlOpenInMainEditor: 'velorix-downloads-first-url-open-editor',
  getOutputDir: 'velorix-downloads-get-output-dir',
  openOutputDir: 'velorix-downloads-open-output-dir',
  getCliOptions: 'velorix-downloads-get-cli-options',
  setCliOptions: 'velorix-downloads-set-cli-options',
  pickOutputDir: 'velorix-downloads-pick-output-dir',
  clearOutputDir: 'velorix-downloads-clear-output-dir',
  pickCookiesFile: 'velorix-downloads-pick-cookies-file',
  clearCookiesFile: 'velorix-downloads-clear-cookies-file',
  clear: 'velorix-downloads-clear',
  clearFinished: 'velorix-downloads-clear-finished',
  getHistory: 'velorix-downloads-get-history',
  getHistoryWeeklySummary: 'velorix-downloads-get-history-weekly-summary',
  downloadsHistoryChanged: 'velorix-downloads-history-changed',
  clearHistory: 'velorix-downloads-clear-history',
  saveVisibleLog: 'velorix-downloads-save-visible-log',
  openQueueOutput: 'velorix-downloads-open-queue-output',
  openHistoryOutput: 'velorix-downloads-open-history-output',
  openQueueOutputInHandler: 'velorix-downloads-open-queue-output-in-handler',
  extractQueueCover: 'velorix-downloads-extract-queue-cover',
  openHistoryOutputInHandler: 'velorix-downloads-open-history-output-in-handler',
  remove: 'velorix-downloads-remove',
  move: 'velorix-downloads-move',
  startQueue: 'velorix-downloads-start-queue',
  startRow: 'velorix-downloads-start-row',
  retryRow: 'velorix-downloads-retry-row',
  cancelRun: 'velorix-downloads-cancel-run',
  getYtdlpPauseState: 'velorix-downloads-ytdlp-pause-state',
  pauseYtdlp: 'velorix-downloads-pause-ytdlp',
  resumeYtdlp: 'velorix-downloads-resume-ytdlp',
  /** §4.1 — частичное сохранение раскрытых секций окна загрузок. */
  mergeUiPanels: 'velorix-downloads-merge-ui-panels',
  /** Мост во главное окно / инспектор без доступа preload загрузок к каналам renderer. */
  bridgeOpenInspector: 'velorix-downloads-bridge-open-inspector',
  bridgeFocusMainEditor: 'velorix-downloads-bridge-focus-main',
  bridgeOpenEnginePaths: 'velorix-downloads-bridge-open-engine-paths',
  bridgeOpenAbout: 'velorix-downloads-bridge-open-about'
} as const

export type MainWindowIpcChannel = (typeof mainWindowIpc)[keyof typeof mainWindowIpc]
export type DownloadsIpcChannel = (typeof downloadsIpc)[keyof typeof downloadsIpc]
