/**
 * Единый реестр строк IPC между main и preload/renderer.
 * Имена каналов не дублируем литералами — импортируем отсюда, чтобы main и preload не расходились.
 */

/** Главное окно: invoke/handle + подписки на события из main. */
export const mainWindowIpc = {
  settingsGet: 'fluxalloy:settings-get',
  settingsSetUiLocale: 'fluxalloy:settings-set-ui-locale',
  settingsSetTheme: 'fluxalloy:settings-set-theme',
  settingsSetFfmpegExportEncodePreset: 'fluxalloy:settings-set-ffmpeg-export-encode-preset',
  settingsSetFfmpegExportVideoCodec: 'fluxalloy:settings-set-ffmpeg-export-video-codec',
  settingsSetFfmpegExportContainer: 'fluxalloy:settings-set-ffmpeg-export-container',
  settingsSetFfmpegExportCrf: 'fluxalloy:settings-set-ffmpeg-export-crf',
  settingsSetFfmpegExportAudioBitrate: 'fluxalloy:settings-set-ffmpeg-export-audio-bitrate',
  settingsSetFfmpegExportAudioMode: 'fluxalloy:settings-set-ffmpeg-export-audio-mode',
  settingsSetFfmpegExportVideoBitrate: 'fluxalloy:settings-set-ffmpeg-export-video-bitrate',
  settingsSetFfmpegExportTwoPass: 'fluxalloy:settings-set-ffmpeg-export-two-pass',
  settingsSetFfmpegExportEconomyMode: 'fluxalloy:settings-set-ffmpeg-export-economy-mode',
  settingsSetFfmpegExportBenchmarkLoadThreshold:
    'fluxalloy:settings-set-ffmpeg-export-benchmark-load-threshold',
  settingsSetFfmpegExportHwDecode: 'fluxalloy:settings-set-ffmpeg-export-hw-decode',
  settingsSetFfmpegExportExtraArgsLine: 'fluxalloy:settings-set-ffmpeg-export-extra-args-line',
  settingsSetFfmpegExportBatchOutputSuffix:
    'fluxalloy:settings-set-ffmpeg-export-batch-output-suffix',
  settingsSetFfmpegExportBatchOutputDirectory:
    'fluxalloy:settings-set-ffmpeg-export-batch-output-dir',
  settingsSetEditorUrlPasteBehavior: 'fluxalloy:settings-set-editor-url-paste-behavior',
  settingsSetFfmpegExportFps: 'fluxalloy:settings-set-ffmpeg-export-fps',
  settingsSetFfmpegExportScalePreset: 'fluxalloy:settings-set-ffmpeg-export-scale-preset',
  settingsSetFfmpegExportVideoTransform: 'fluxalloy:settings-set-ffmpeg-export-video-transform',
  settingsSetFfmpegExportCropPreset: 'fluxalloy:settings-set-ffmpeg-export-crop-preset',
  settingsSetFfmpegExportAudioGainDb: 'fluxalloy:settings-set-ffmpeg-export-audio-gain-db',
  settingsSetFfmpegExportStripMetadata: 'fluxalloy:settings-set-ffmpeg-export-strip-metadata',
  settingsSetFfmpegExportStripChapters: 'fluxalloy:settings-set-ffmpeg-export-strip-chapters',
  settingsSetFfmpegExportSubtitleMode: 'fluxalloy:settings-set-ffmpeg-export-subtitle-mode',
  settingsSetFfmpegExportVideoDenoise: 'fluxalloy:settings-set-ffmpeg-export-video-denoise',
  settingsSetFfmpegExportVideoDeband: 'fluxalloy:settings-set-ffmpeg-export-video-deband',
  settingsSetFfmpegExportVideoHisteq: 'fluxalloy:settings-set-ffmpeg-export-video-histeq',
  settingsSetFfmpegExportVideoLut3d: 'fluxalloy:settings-set-ffmpeg-export-video-lut3d',
  settingsSetFfmpegExportVideoSharpen: 'fluxalloy:settings-set-ffmpeg-export-video-sharpen',
  settingsSetFfmpegExportVideoEqPreset: 'fluxalloy:settings-set-ffmpeg-export-video-eq-preset',
  settingsSetFfmpegExportVideoGrain: 'fluxalloy:settings-set-ffmpeg-export-video-grain',
  settingsSetFfmpegExportVideoVignette: 'fluxalloy:settings-set-ffmpeg-export-video-vignette',
  settingsSetFfmpegExportVideoBlur: 'fluxalloy:settings-set-ffmpeg-export-video-blur',
  settingsSetFfmpegExportVideoDeinterlace: 'fluxalloy:settings-set-ffmpeg-export-video-deinterlace',
  settingsSetFfmpegExportVideoHue: 'fluxalloy:settings-set-ffmpeg-export-video-hue',
  settingsSetFfmpegExportAudioNormalize: 'fluxalloy:settings-set-ffmpeg-export-audio-normalize',
  settingsSetFfmpegExportUserPresets: 'fluxalloy:settings-set-ffmpeg-export-user-presets',
  settingsApplyFfmpegExportSnapshot: 'fluxalloy:settings-apply-ffmpeg-export-snapshot',
  settingsSetFfmpegSnapshotFormat: 'fluxalloy:settings-set-ffmpeg-snapshot-format',
  settingsSetEnginePaths: 'fluxalloy:settings-set-engine-paths',
  /** §4.1 — частичное обновление раскрытых секций главного окна (persist в settings.json). */
  settingsMergeMainWindowUiPanels: 'fluxalloy:settings-merge-main-window-ui-panels',
  pickEngineExecutable: 'fluxalloy:pick-engine-executable',
  enginesStatus: 'fluxalloy:engines-status',
  enginesShouldOfferDownload: 'fluxalloy:engines-should-offer-download',
  enginesDownload: 'fluxalloy:engines-download',
  enginesCheckUpdatesAndDownload: 'fluxalloy:engines-check-updates-and-download',
  enginesClearUserBin: 'fluxalloy:engines-clear-user-bin',
  enginesProbeHwEncoders: 'fluxalloy:engines-probe-hw-encoders',
  enginesProgress: 'fluxalloy:engines-progress',
  openVideoDialog: 'fluxalloy:open-video-dialog',
  openVideoFolderDialog: 'fluxalloy:open-video-folder-dialog',
  previewGrantPath: 'fluxalloy:preview-grant-path',
  persistLastSource: 'fluxalloy:persist-last-source',
  restoreLastSource: 'fluxalloy:restore-last-source',
  mediaProbe: 'fluxalloy:media-probe',
  terminalHints: 'fluxalloy:terminal-hints',
  terminalRun: 'fluxalloy:terminal-run',
  knowledgeListArticles: 'fluxalloy:knowledge-list-articles',
  knowledgeReadArticle: 'fluxalloy:knowledge-read-article',
  clipboardReadText: 'fluxalloy:clipboard-read-text',
  clipboardWriteText: 'fluxalloy:clipboard-write-text',
  saveTextWithDialog: 'fluxalloy:save-text-with-dialog',
  appAboutInfo: 'fluxalloy:app-about-info',
  diagnosticsListFolders: 'fluxalloy:diagnostics-list-folders',
  diagnosticsOpenFolder: 'fluxalloy:diagnostics-open-folder',
  diagnosticsOpenMainLog: 'fluxalloy:diagnostics-open-main-log',
  diagnosticsCreateSupportZip: 'fluxalloy:diagnostics-create-support-zip',
  diagnosticsMaintenanceSnapshot: 'fluxalloy:diagnostics-maintenance-snapshot',
  diagnosticsCleanMaintenance: 'fluxalloy:diagnostics-clean-maintenance',
  processingHistoryGet: 'fluxalloy:processing-history-get',
  processingHistoryWeeklySummary: 'fluxalloy:processing-history-weekly-summary',
  processingHistoryClear: 'fluxalloy:processing-history-clear',
  processingHistoryOpenOutput: 'fluxalloy:processing-history-open-output',
  processingHistoryOpenInputInHandler: 'fluxalloy:processing-history-open-input-in-handler',
  processingHistoryRepeatWorkflowScenario: 'fluxalloy:processing-history-repeat-workflow-scenario',
  processingHistoryChanged: 'fluxalloy:processing-history-changed',
  windowsExplorerContextMenuStatus: 'fluxalloy:windows-explorer-context-menu-status',
  windowsExplorerContextMenuSetEnabled: 'fluxalloy:windows-explorer-context-menu-set-enabled',
  windowsExplorerContextMenuRegisterNow: 'fluxalloy:windows-explorer-context-menu-register-now',
  windowsExplorerContextMenuUnregister: 'fluxalloy:windows-explorer-context-menu-unregister',
  windowsFileAssociationStatus: 'fluxalloy:windows-file-association-status',
  windowsFileAssociationSetEnabled: 'fluxalloy:windows-file-association-set-enabled',
  windowsFileAssociationRegisterNow: 'fluxalloy:windows-file-association-register-now',
  windowsFileAssociationUnregister: 'fluxalloy:windows-file-association-unregister',
  openWindowsDefaultAppsSettings: 'fluxalloy:open-windows-default-apps-settings',
  openDownloadsWindow: 'fluxalloy:open-downloads-window',
  /** §9 — отдельное окно инспектора ffprobe (`#inspector`). */
  openInspectorWindow: 'fluxalloy:open-inspector-window',
  inspectorBootstrap: 'fluxalloy:inspector-bootstrap',
  /** Main → renderer окна инспектора: проанализировать указанный путь. */
  inspectorTargetMediaPath: 'fluxalloy:inspector-target-media-path',
  exportStart: 'fluxalloy:export-start',
  exportBenchmarkEncoders: 'fluxalloy:export-benchmark-encoders',
  exportBenchmarkProgress: 'fluxalloy:export-benchmark-progress',
  extractFrames: 'fluxalloy:extract-frames',
  extractFramesProgress: 'fluxalloy:extract-frames-progress',
  mediaUtilitiesRepairRemux: 'fluxalloy:media-utilities-repair-remux',
  mediaUtilitiesCheckIntegrity: 'fluxalloy:media-utilities-check-integrity',
  mediaUtilitiesGenerateNoise: 'fluxalloy:media-utilities-generate-noise',
  mediaUtilitiesComputeFileHash: 'fluxalloy:media-utilities-compute-file-hash',
  mediaUtilitiesConvertImage: 'fluxalloy:media-utilities-convert-image',
  exportResolveBundledLutCubePath: 'fluxalloy:export-resolve-bundled-lut-cube-path',
  exportCancel: 'fluxalloy:export-cancel',
  exportOpenOutput: 'fluxalloy:export-open-output',
  exportProgress: 'fluxalloy:export-progress',
  batchExportGetSnapshot: 'fluxalloy:batch-export-get-snapshot',
  batchExportPickFiles: 'fluxalloy:batch-export-pick-files',
  batchExportPickFolder: 'fluxalloy:batch-export-pick-folder',
  batchExportPickOutputFolder: 'fluxalloy:batch-export-pick-output-folder',
  batchExportRevealSharedOutputFolder: 'fluxalloy:batch-export-reveal-shared-output-folder',
  batchExportAddPaths: 'fluxalloy:batch-export-add-paths',
  batchExportRemoveRows: 'fluxalloy:batch-export-remove-rows',
  batchExportClear: 'fluxalloy:batch-export-clear',
  batchExportMoveRow: 'fluxalloy:batch-export-move-row',
  batchExportReorderRow: 'fluxalloy:batch-export-reorder-row',
  batchExportSetConcurrency: 'fluxalloy:batch-export-set-concurrency',
  batchExportStart: 'fluxalloy:batch-export-start',
  batchExportCancel: 'fluxalloy:batch-export-cancel',
  batchExportRetryFailed: 'fluxalloy:batch-export-retry-failed',
  batchExportRetryRows: 'fluxalloy:batch-export-retry-rows',
  batchExportClearCompleted: 'fluxalloy:batch-export-clear-completed',
  batchExportAddFromDownloadsDone: 'fluxalloy:batch-export-add-from-downloads-done',
  batchExportAddFromHistoryInputs: 'fluxalloy:batch-export-add-from-history-inputs',
  batchExportRetryFailedAndStart: 'fluxalloy:batch-export-retry-failed-and-start',
  batchExportListInputPaths: 'fluxalloy:batch-export-list-input-paths',
  batchExportListOutputPaths: 'fluxalloy:batch-export-list-output-paths',
  batchExportRemoveWaiting: 'fluxalloy:batch-export-remove-waiting',
  batchExportOpenInput: 'fluxalloy:batch-export-open-input',
  batchExportSnapshot: 'fluxalloy:batch-export-snapshot',
  snapshotFrame: 'fluxalloy:snapshot-frame',
  logRenderer: 'fluxalloy:log-renderer',
  previewOpened: 'fluxalloy:preview-opened',
  themeChanged: 'fluxalloy:theme-changed',
  uiLocaleChanged: 'fluxalloy:ui-locale-changed',
  openEnginePaths: 'fluxalloy:open-engine-paths',
  /** Main → renderer: открыть единое окно настроек; payload — `AppSettingsDialogSection` или пусто. */
  openSettings: 'fluxalloy:open-settings',
  enginePathsChanged: 'fluxalloy:engine-paths-changed',
  settingsBackupExport: 'fluxalloy:settings-backup-export',
  settingsBackupImport: 'fluxalloy:settings-backup-import',
  settingsResetToDefaults: 'fluxalloy:settings-reset-to-defaults',
  /** Main → renderer: полная замена settings.json после импорта из меню «Сервис». */
  settingsBackupImported: 'fluxalloy:settings-backup-imported',
  openAbout: 'fluxalloy:open-about',
  openExternalFilterScript: 'fluxalloy:open-external-filter-script',
  externalFilterScriptPickFile: 'fluxalloy:external-filter-script-pick-file',
  externalFilterScriptApply: 'fluxalloy:external-filter-script-apply',
  /** §10/§11 — реестр сценариев и задач в userData/workflows. */
  workflowScenariosList: 'fluxalloy:workflow-scenarios-list',
  workflowScenariosGet: 'fluxalloy:workflow-scenarios-get',
  workflowScenariosSave: 'fluxalloy:workflow-scenarios-save',
  workflowScenariosDelete: 'fluxalloy:workflow-scenarios-delete',
  scheduledTasksList: 'fluxalloy:scheduled-tasks-list',
  scheduledTasksSave: 'fluxalloy:scheduled-tasks-save',
  scheduledTasksDelete: 'fluxalloy:scheduled-tasks-delete',
  scheduledTasksSetEnabled: 'fluxalloy:scheduled-tasks-set-enabled',
  workflowPickWatchFolder: 'fluxalloy:workflow-pick-watch-folder',
  /** Renderer → main: поставить прогон сценария по уже открытому медиафайлу. */
  workflowRunScenarioOnFile: 'fluxalloy:workflow-run-scenario-on-file',
  workflowRunScenarioOnUrl: 'fluxalloy:workflow-run-scenario-on-url',
  workflowCapabilities: 'fluxalloy:workflow-capabilities',
  /** Main → renderer: новый файл в папке задачи watch-folder. */
  workflowWatchFolderDetected: 'fluxalloy:workflow-watch-folder-detected',
  workflowWatchFolderRunFinished: 'fluxalloy:workflow-watch-folder-run-finished',
  /** Main → renderer: открыть планировщик / конструктор сценариев. */
  openWorkflowPlanner: 'fluxalloy:open-workflow-planner',
  openWorkflowScenarioBuilder: 'fluxalloy:open-workflow-scenario-builder',
  /** Main → все окна с главным preload: актуальный снимок `mainWindowUiPanels` после merge §4.1. */
  mainWindowUiPanelsChanged: 'fluxalloy:main-window-ui-panels-changed',
  /** Main → главное окно: снимок `downloadsWindowUiPanels` после merge (вкладка «Загрузки» ↔ pop-out). */
  downloadsWindowUiPanelsChanged: 'fluxalloy:downloads-window-ui-panels-changed',
  /** Main → вкладка «Загрузки» и pop-out: каталог вывода yt-dlp после pick/clear/merge settings. */
  downloadsOutputDirectoryChanged: 'fluxalloy:downloads-output-directory-changed',
  /** Main → вкладка «Загрузки» и pop-out: yt-dlp CLI/options изменились (клиенты делают getCliOptions). */
  downloadsCliOptionsChanged: 'fluxalloy:downloads-cli-options-changed'
} as const

/** Окно yt-dlp: invoke/handle + push (`queueSnapshot`, `log`). */
export const downloadsIpc = {
  queueSnapshot: 'fluxalloy-downloads-state',
  log: 'fluxalloy-downloads-log',
  getSnapshot: 'fluxalloy-downloads-get-snapshot',
  addLines: 'fluxalloy-downloads-add-lines',
  /** §6 — первый URL из текста: скачать одной строкой и открыть результат в главном редакторе. */
  downloadFirstUrlOpenInMainEditor: 'fluxalloy-downloads-first-url-open-editor',
  getOutputDir: 'fluxalloy-downloads-get-output-dir',
  openOutputDir: 'fluxalloy-downloads-open-output-dir',
  getCliOptions: 'fluxalloy-downloads-get-cli-options',
  setCliOptions: 'fluxalloy-downloads-set-cli-options',
  pickOutputDir: 'fluxalloy-downloads-pick-output-dir',
  clearOutputDir: 'fluxalloy-downloads-clear-output-dir',
  pickCookiesFile: 'fluxalloy-downloads-pick-cookies-file',
  clearCookiesFile: 'fluxalloy-downloads-clear-cookies-file',
  clear: 'fluxalloy-downloads-clear',
  clearFinished: 'fluxalloy-downloads-clear-finished',
  getHistory: 'fluxalloy-downloads-get-history',
  getHistoryWeeklySummary: 'fluxalloy-downloads-get-history-weekly-summary',
  downloadsHistoryChanged: 'fluxalloy-downloads-history-changed',
  clearHistory: 'fluxalloy-downloads-clear-history',
  saveVisibleLog: 'fluxalloy-downloads-save-visible-log',
  openQueueOutput: 'fluxalloy-downloads-open-queue-output',
  openHistoryOutput: 'fluxalloy-downloads-open-history-output',
  openQueueOutputInHandler: 'fluxalloy-downloads-open-queue-output-in-handler',
  extractQueueCover: 'fluxalloy-downloads-extract-queue-cover',
  openHistoryOutputInHandler: 'fluxalloy-downloads-open-history-output-in-handler',
  remove: 'fluxalloy-downloads-remove',
  move: 'fluxalloy-downloads-move',
  startQueue: 'fluxalloy-downloads-start-queue',
  startRow: 'fluxalloy-downloads-start-row',
  retryRow: 'fluxalloy-downloads-retry-row',
  cancelRun: 'fluxalloy-downloads-cancel-run',
  getYtdlpPauseState: 'fluxalloy-downloads-ytdlp-pause-state',
  pauseYtdlp: 'fluxalloy-downloads-pause-ytdlp',
  resumeYtdlp: 'fluxalloy-downloads-resume-ytdlp',
  /** §4.1 — частичное сохранение раскрытых секций окна загрузок. */
  mergeUiPanels: 'fluxalloy-downloads-merge-ui-panels',
  /** Мост во главное окно / инспектор без доступа preload загрузок к каналам renderer. */
  bridgeOpenInspector: 'fluxalloy-downloads-bridge-open-inspector',
  bridgeFocusMainEditor: 'fluxalloy-downloads-bridge-focus-main',
  bridgeOpenEnginePaths: 'fluxalloy-downloads-bridge-open-engine-paths',
  bridgeOpenAbout: 'fluxalloy-downloads-bridge-open-about'
} as const

export type MainWindowIpcChannel = (typeof mainWindowIpc)[keyof typeof mainWindowIpc]
export type DownloadsIpcChannel = (typeof downloadsIpc)[keyof typeof downloadsIpc]
