import type { AppUiLocale } from './app-ui-locale'

/** Fallback category when token is absent from maps and JSON has no `category`. */
export const YTDLP_HINT_TOKEN_CATEGORY_RU: Readonly<Record<string, string>> = {
  '--help': 'Справка',
  '--version': 'Справка',
  '--list-extractors': 'Справка',
  '-F': 'Форматы и кодеки',
  '-f': 'Форматы и кодеки',
  '--list-formats': 'Форматы и кодеки',
  '-g': 'Форматы и кодеки',
  '-J': 'Вывод и журнал',
  '--dump-single-json': 'Вывод и журнал',
  '--print': 'Вывод и журнал',
  '--print-to-file': 'Вывод и журнал',
  best: 'Форматы и кодеки',
  '--merge-output-format': 'Форматы и кодеки',
  '-x': 'Форматы и кодеки',
  '--audio-format': 'Форматы и кодеки',
  '--proxy': 'Сеть и HTTP',
  '--limit-rate': 'Сеть и HTTP',
  '--no-check-certificates': 'Сеть и HTTP',
  '--user-agent': 'Сеть и HTTP',
  '--referer': 'Сеть и HTTP',
  '--add-header': 'Сеть и HTTP',
  '--socket-timeout': 'Сеть и HTTP',
  '--retries': 'Сеть и HTTP',
  '--fragment-retries': 'Сеть и HTTP',
  '--concurrent-fragments': 'Сеть и HTTP',
  '--force-ipv4': 'Сеть и HTTP',
  '--force-ipv6': 'Сеть и HTTP',
  '-N': 'Сеть и HTTP',
  '--impersonate': 'Доступ и cookies',
  chrome: 'Доступ и cookies',
  '--cookies': 'Доступ и cookies',
  '--cookies-from-browser': 'Доступ и cookies',
  '--ap-mso': 'Доступ и cookies',
  '--continue': 'Загрузка: режим и файлы',
  '--no-live': 'Загрузка: режим и файлы',
  '--skip-download': 'Загрузка: режим и файлы',
  '--download-sections': 'Загрузка: режим и файлы',
  '--no-part': 'Загрузка: режим и файлы',
  '--no-overwrites': 'Загрузка: режим и файлы',
  '--no-cache-dir': 'Загрузка: режим и файлы',
  '--restrict-filenames': 'Загрузка: режим и файлы',
  '--windows-filenames': 'Загрузка: режим и файлы',
  '-o': 'Загрузка: режим и файлы',
  '-a': 'Загрузка: режим и файлы',
  '--playlist-end': 'Плейлист и фильтры',
  '--playlist-items': 'Плейлист и фильтры',
  '--no-playlist': 'Плейлист и фильтры',
  '--dateafter': 'Плейлист и фильтры',
  '--extractor-args': 'Плейлист и фильтры',
  '--geo-bypass': 'Плейлист и фильтры',
  '--write-subs': 'Субтитры, обложки и метаданные',
  '--embed-subs': 'Субтитры, обложки и метаданные',
  '--write-thumbnail': 'Субтитры, обложки и метаданные',
  '--write-info-json': 'Субтитры, обложки и метаданные',
  '--write-description': 'Субтитры, обложки и метаданные',
  '--write-comments': 'Субтитры, обложки и метаданные',
  '--embed-metadata': 'Субтитры, обложки и метаданные',
  '--embed-thumbnail': 'Субтитры, обложки и метаданные',
  '--ffmpeg-location': 'Субтитры, обложки и метаданные',
  '--newline': 'Вывод и журнал',
  '--progress': 'Вывод и журнал',
  '--no-warnings': 'Вывод и журнал'
}

export const YTDLP_HINT_TOKEN_CATEGORY_EN: Readonly<Record<string, string>> = {
  '--help': 'Help',
  '--version': 'Help',
  '--list-extractors': 'Help',
  '-F': 'Formats & codecs',
  '-f': 'Formats & codecs',
  '--list-formats': 'Formats & codecs',
  '-g': 'Formats & codecs',
  '-J': 'Output & logging',
  '--dump-single-json': 'Output & logging',
  '--print': 'Output & logging',
  '--print-to-file': 'Output & logging',
  best: 'Formats & codecs',
  '--merge-output-format': 'Formats & codecs',
  '-x': 'Formats & codecs',
  '--audio-format': 'Formats & codecs',
  '--proxy': 'Network & HTTP',
  '--limit-rate': 'Network & HTTP',
  '--no-check-certificates': 'Network & HTTP',
  '--user-agent': 'Network & HTTP',
  '--referer': 'Network & HTTP',
  '--add-header': 'Network & HTTP',
  '--socket-timeout': 'Network & HTTP',
  '--retries': 'Network & HTTP',
  '--fragment-retries': 'Network & HTTP',
  '--concurrent-fragments': 'Network & HTTP',
  '--force-ipv4': 'Network & HTTP',
  '--force-ipv6': 'Network & HTTP',
  '-N': 'Network & HTTP',
  '--impersonate': 'Access & cookies',
  chrome: 'Access & cookies',
  '--cookies': 'Access & cookies',
  '--cookies-from-browser': 'Access & cookies',
  '--ap-mso': 'Access & cookies',
  '--continue': 'Download: mode & files',
  '--no-live': 'Download: mode & files',
  '--skip-download': 'Download: mode & files',
  '--download-sections': 'Download: mode & files',
  '--no-part': 'Download: mode & files',
  '--no-overwrites': 'Download: mode & files',
  '--no-cache-dir': 'Download: mode & files',
  '--restrict-filenames': 'Download: mode & files',
  '--windows-filenames': 'Download: mode & files',
  '-o': 'Download: mode & files',
  '-a': 'Download: mode & files',
  '--playlist-end': 'Playlist & filters',
  '--playlist-items': 'Playlist & filters',
  '--no-playlist': 'Playlist & filters',
  '--dateafter': 'Playlist & filters',
  '--extractor-args': 'Playlist & filters',
  '--geo-bypass': 'Playlist & filters',
  '--write-subs': 'Subtitles, thumbnails & metadata',
  '--embed-subs': 'Subtitles, thumbnails & metadata',
  '--write-thumbnail': 'Subtitles, thumbnails & metadata',
  '--write-info-json': 'Subtitles, thumbnails & metadata',
  '--write-description': 'Subtitles, thumbnails & metadata',
  '--write-comments': 'Subtitles, thumbnails & metadata',
  '--embed-metadata': 'Subtitles, thumbnails & metadata',
  '--embed-thumbnail': 'Subtitles, thumbnails & metadata',
  '--ffmpeg-location': 'Subtitles, thumbnails & metadata',
  '--newline': 'Output & logging',
  '--progress': 'Output & logging',
  '--no-warnings': 'Output & logging'
}

export function ytdlpHintTokenCategory(token: string, locale: AppUiLocale): string | undefined {
  const m = locale === 'en' ? YTDLP_HINT_TOKEN_CATEGORY_EN : YTDLP_HINT_TOKEN_CATEGORY_RU
  return m[token]
}
